### ISSUE TITLE
NetworkInterceptor just shows the last Cookie

### ISSUE THREAD

**Issue by tsuharesu** [facebook/stetho#115]
When sending requests with more than one Cookie, Stetho is only showing the last on the the Inspector.

![request_bin](https://cloud.githubusercontent.com/assets/808267/6933208/a3f2d58a-d7fa-11e4-9632-34322944edc2.PNG)
![stetho_inspect](https://cloud.githubusercontent.com/assets/808267/6933210/a8ee8a3e-d7fa-11e4-9434-2422669c406f.PNG)
![stetho_inspect_02](https://cloud.githubusercontent.com/assets/808267/6933228/cd339542-d7fa-11e4-9f11-aa0b1a14e5ee.PNG)

Using:
```java
compile 'com.facebook.stetho:stetho:1.0.1'
compile 'com.facebook.stetho:stetho-okhttp:1.0.1'
compile 'com.squareup.okhttp:okhttp:2.3.0'
```
And to add Cookies to OkHttp I'm using another NetworkInterceptor.

Here a project I put together to help with debug: https://github.com/tsuharesu/StethoBug

**Comment by jasta** [comment]
Hmm, good catch.  This appears to be a bug in https://github.com/facebook/stetho/blob/master/stetho/src/main/java/com/facebook/stetho/inspector/network/NetworkEventReporterImpl.java#L280.  I don't know exactly what the protocol expects us to do, but I'm betting it's probably encode the value as a JSON array.

**Comment by jasta** [comment]
Found it.  The protocol uses a `'\n'` character to split multiple headers with the same name, according to: https://chromium.googlesource.com/chromium/blink/+/master/Source/devtools/front_end/sdk/NetworkManager.js function _headersMapToHeadersArray.  Undocumented, but whatever, I can comply :)

**Comment by tsuharesu** [comment]
Nice! Thanks for looking at this :)
