### ISSUE TITLE
Chrome ARC support

### ISSUE THREAD

**Issue by hzsweers** [facebook/stetho#139]
Not sure if this is possible, but figured I'd open an issue to get the discussion going.

Google recently release ARC for Chrome, which allows you to run Android apps in Chrome. In my short experience with it, it's *very* smooth and could possibly be a debugging alternative to the built-in emulator or genymotion for our backend services teams to use in debugging. It can speak ADB, but I can't find anything about remote device inspection yet.

https://developer.chrome.com/apps/getstarted_arc

Here's a stackoverflow question someone started relating to using Chrome's device inspection (using their tag, so hopefully answered soon): http://stackoverflow.com/questions/29456032/debug-webview-with-chrome-on-arc

**Comment by jasta** [comment]
How do you envision this integration would go with Stetho?  I'm having a hard time understand what you would be trying to actually debug or why Stetho itself wouldn't just work as-is?

**Comment by hzsweers** [comment]
Well, my point is that it doesn't work as-is. Not all of our backend guys have android devices, and less want to deal with the emulator. If stetho was accessible via app running in ARC, that would be an immense utility for them.

**Comment by jasta** [comment]
I'm not really familiar with ARC or what ARC is doing to break even WebView's devtools support.  If you could provide some more information I might be able to help you figure out what's needed or maybe patch Stetho to support it.  But as-is, I have too little information to proceed...

**Comment by hzsweers** [comment]
http://arstechnica.com/gadgets/2015/04/googles-arc-opens-up-to-developers-runs-android-apps-on-most-desktop-oses/

I'm not sure what's going on under the hood for it either, just wanted to put up this issue to get the conversation going. It can speak ADB, so hopefully google has plans to support remote device debugging as well. Since, you know, it is running in *Chrome* :stuck_out_tongue:

**Comment by hzsweers** [comment]
It looks like Google's looking into it though: https://code.google.com/p/chromium/issues/detail?id=422106
