### ISSUE TITLE
Implement Elements tab

### ISSUE THREAD

**Issue by jasta** [facebook/stetho#14]
Implement Elements tab to support DOM / view hierarchy inspection

**Comment by goncalossilva** [comment]
Yes, please!

**Comment by jasta** [comment]
We're working on it: https://github.com/rickbrew/stetho/commit/b87a818d6e3b6bf1e68e0e4c8aa5e76b6eabb53e :)

**Comment by felipecsl** [comment]
is this merged in already?

**Comment by rickbrew** [comment]
Woops, nope it's still over in the elements branch.

**Comment by jasta** [comment]
@felipecsl soon..... :)

**Comment by felipecsl** [comment]
cant wait :watch:  :)
