### ISSUE TITLE
Auto discover in dumpapp gives bad information when multiple stetho enabled processes 

### ISSUE THREAD

**Issue by longinoa** [facebook/stetho#149]
If you have multiple processes the exception is "No stetho-enabled process running" It should be a list of them
https://gist.github.com/b1c492f1a61c97da1fd0

**Comment by jasta** [comment]
This is actually working fine for me.  Are you sure the processes weren't crashing?  If you can repro this again, capture the output of `adb shell cat /proc/net/unix` (it's how dumpapp produces the list).
