### ISSUE TITLE
Implement Timeline tab

### ISSUE THREAD

**Issue by jasta** [facebook/stetho#15]
How exactly, I'm not sure yet :)

**Comment by banshee** [comment]
I'd like an api just to inject our own values into the timeline.

**Comment by jasta** [comment]
That's what we want too, ideally :)  We just haven't done the work yet to
think through the API and how we want to build upon it.  We actually have
some more general extensibility API issues that this butts up against and
so we're trying to be a bit more measured about how we approach this one.

That's not to say the PRs are not welcome though :)

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jasta** [comment]
Not implemented but not a priority.  Dropping the task for now.

**Comment by Kiran89kumar** [comment]
Any update on this?
