### ISSUE TITLE
java.lang.RuntimeException: Prefs change detected for unknown key=ADMS_PauseDate

### ISSUE THREAD

**Issue by rps700** [facebook/stetho#155]
Constantly getting below mentioned crash while actively inspecting with Stetho. Thought about reporting it. But overall very impressive tool! Thanks for developing it. 

Runtime error log: 
E/AndroidRuntime(17259): java.lang.RuntimeException: Prefs change detected for unknown key=ADMS_PauseDate
E/AndroidRuntime(17259): 	at com.facebook.stetho.inspector.domstorage.DOMStoragePeerManager$DevToolsSharedPreferencesListener.onSharedPreferenceChanged(DOMStoragePeerManager.java:145)
E/AndroidRuntime(17259): 	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:475)
E/AndroidRuntime(17259): 	at android.app.SharedPreferencesImpl$EditorImpl.access$600(SharedPreferencesImpl.java:303)
E/AndroidRuntime(17259): 	at android.app.SharedPreferencesImpl$EditorImpl$3.run(SharedPreferencesImpl.java:483)
E/AndroidRuntime(17259): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(17259): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(17259): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(17259): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime(17259): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(17259): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(17259): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
E/AndroidRuntime(17259): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
E/AndroidRuntime(17259): 	at dalvik.system.NativeStart.main(Native Method)
D/ChromeDevtoolsServer(17726): Method not implemented: Not implemented: Runtime.enable
W/BaseRuntimeLoader(17726): don't searchcom.lge.telephony.msim.QcomMSimTelephonyManagerAdaptor class
W/BaseRuntimeLoader(17726): don't searchcom.lge.telephony.msim.MtkMSimTelephonyManagerAdaptor class
W/BaseRuntimeLoader(17726): don't searchcom.lge.telephony.msim.QcomMSimTelephonyManagerAdaptor class
W/BaseRuntimeLoader(17726): don't searchcom.lge.telephony.msim.MtkMSimTelephonyManagerAdaptor class

**Comment by jasta** [comment]
I noticed a few other folks reporting this at Droidcon Montreal as well and I think I know why its happening.  I'll take a crack at a fix soon.

We have a few other lame mistakes in the recent release so hopefully we can put together a quick bug fix release this week.

**Comment by jasta** [comment]
Collapsing into #151
