### ISSUE TITLE
Can not recognize non .db file as sqlite3 database

### ISSUE THREAD

**Issue by Honghe** [facebook/stetho#165]
Such as database end with `.db3`, in this case, stetho can not treat it as sqlite3 database. Is this design intent?

**Comment by jasta** [comment]
We support this in the latest release by allowing you to provide your own
db file traversal interface however the extensibility API needs some work.
Take a look at Database.java's constructor.  I'm on my mobile now so I
can't easily look up the specific PR which addressed this but in it there
is an example of how to provide a custom interface yourself.

**Comment by Honghe** [comment]
@jasta Thanks!
