### ISSUE TITLE
Search View Hierarchy by Class Name 

### ISSUE THREAD

**Issue by yrizk** [facebook/stetho#179]
First off, great work guys! Is the search function I mentioned above supposed to be working? it it isn't for me. Android's monitor does support it, but the whole tool is flimsy at best. This is way more stable.

**Comment by jasta** [comment]
I'm not familiar with this feature.  Where is it in the Chrome DevTools UI?

**Comment by yrizk** [comment]
Well, a search field does pop if you hit Cmd / (control) + F if the focus is in the main view hierarchy tab

**Comment by rickbrew** [comment]
This might be powered by `DOM.performSearch`, `DOM.getSearchResults`, `DOM.discardSearchResult` ?

**Comment by jasta** [comment]
Oh I see it now.  Yes, that does look very handy.  We have a new release rolling right now but we'll take a look at this for the next one.

**Comment by jasta** [comment]
Also, pull requests welcome :P
