### ISSUE TITLE
top activity with android:process attribute  different with default process can't be inspect(Elements Tab in chrome)

### ISSUE THREAD

**Issue by kissazi2** [facebook/stetho#185]
```xml
	<activity
            android:name="com.kissazi2.MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="com.kissazi2.SecondActivity"
			android:process=":process2"
            android:label="@string/app_name" >
        </activity>
		
		<activity
            android:name="com.kissazi2.TopActivity"
			android:process=":process2"
            android:label="@string/app_name" >
        </activity>
```

when Activity start as the order : MainAvtivity → SecondActivity → TopActivity，the MainActivity can be inspect 。the TopActivity can't be inspect which in chrome's Elements tab can't find TopActivity

**Comment by jasta** [comment]
Stetho attaches to a specific process when you click "Inspect".  To see other processes, return to `chrome://inspect` and click the appropriate process' "Inspect" link.

**Comment by kissazi2** [comment]
I had tried it,but still can't see TopActivity in Elements Tab.

**Comment by jasta** [comment]
Is this using the latest (1.1.1)?  Hmm, can you check logcat for any
interesting messages from stetho?
