### ISSUE TITLE
Implement Screencasting

### ISSUE THREAD

**Issue by auchenberg** [facebook/stetho#189]
Chrome DevTools supports [screencasting](http://blog.chromium.org/2013/12/chrome-devtools-for-mobile-emulate-and.html) of the screen of the attached device. Since Stetho is using the embedded Chrome DevTools via ``chrome://inspect `` it's straightforward to implement, as DevTools is already launched with the correct parameters.

[![ScreenShot](http://img.youtube.com/vi/Q7rEFEMpwe4/maxresdefault.jpg)](http://youtu.be/Q7rEFEMpwe4)

#### Steps to implement:

- Reply ``{ result: true }`` to the ``Page.canScreencast`` method request made from DevTools.

- Implement logic to capture screenshot of running Android app as JPEG, base64 encode the image and emit a ``Page.screencastFrame`` event, with the following data-structure:

```javascript
{
    method: 'Page.screencastFrame',
    params: {
        data: <base64 image>,
        metadata: {
            pageScaleFactor: 1,
            offsetTop: 0,
            deviceWidth: <width>,
            deviceHeight: <height>,
            scrollOffsetX: 0,
            scrollOffsetY: 0
        }
    }
}
```

**Comment by jasta** [comment]
You seem to have implemented this already based on the screenshot?  Should
I expect a PR? :)

**Comment by auchenberg** [comment]
Nah, its a screenshot from the introduction video showing Paul Irish demoing it in Chrome on Android.

I'm not a Java guy so I can't help implement the server part, but I can assist on the DevTools part :)

**Comment by felipecsl** [comment]
I up for implementing this. Will give it a try and ping you if I have any DevTools questions, @auchenberg  :)

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by auchenberg** [comment]
This can be closed now.
