### ISSUE TITLE
Sources tab

### ISSUE THREAD

**Issue by fourlastor** [facebook/stetho#191]
I was wondering how realistic would it be to implement the sources tab.

One way could be using JavaScript sources maps (which as far as I understood don't need to be JavaScript): it could expose the source and let people debug directly from chrome, which would be helpful for example if they're not using IntellijIDEA or Eclipse.

**Comment by jasta** [comment]
Well, the sources to an app don't exist at runtime.  How do you propose
finding them?

You could disassemble the byte code but that seems less useful :)

**Comment by fourlastor** [comment]
I've not much experience in this but I guess the way the Android debugger works could be a starting point, otherwise a gradle plugin to send the source code as an asset which runs only on some build types?

**Comment by jasta** [comment]
A sources jar could work in theory.  I worry it would make the APK much
larger and take more time to deploy.  It would probably not have general
appeal then :/

I'm not so sure either that having the sources would be that useful
either.  The source browser for JavaScript is IMO pretty clunky compared to
intellij.

**Comment by fourlastor** [comment]
You're right, and hopefully the percentage of people not using intellij is very small. I'll focus on other issues then :p
