### ISSUE TITLE
Reattach to DevTools inspector

### ISSUE THREAD

**Issue by felipecsl** [facebook/stetho#194]
Is there a way to reattach an already open devtools inspector after the app has been closed and reopened? It's really annoying having to reopen the devtools window every time. Here's a screenshot to illustrate: 
![screen shot 2015-05-21 at 11 32 36 pm](https://cloud.githubusercontent.com/assets/190648/7765349/d6751a06-0011-11e5-8a91-7eecc44a46d5.png)
I'd be happy to send a PR if anyone sends directions for how to fix this

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jasta** [comment]
Unfortunately we can't really fix this.  Perhaps we should focus on fixing it in Chrome itself?

**Comment by lynfogeek** [comment]
I was wondering if stetho could automatically close the opened devtool when the app process is killed?
It would also be handy to programmatically open a devtool when the app starts (if a stetho is configured to of course).

**Comment by longinoa** [comment]
@lynfogeek  see #161

**Comment by musooff** [comment]
2019! No plan to reopen this issue and actually implement the requested feature?
