### ISSUE TITLE
Make it easier to change the DatabaseFilesProvider

### ISSUE THREAD

**Issue by paour** [facebook/stetho#195]
In 1.1.1, it's very hard to use a different DatabaseFilesProvider than the DefaultDFP, because the instance is private final and it's created at the end of a long, non-configurable chain.

An easier method in the builder (or after build) of changing it would be welcome.

The purpose of changing it is to support applications that do not store their databases in the default location (/data/data/app_id/databases).

**Comment by jasta** [comment]
Agreed, we've been wanting to correct this for some time now.  The `Stetho.initialize` API is really not serving anyone well right now (it's verbose for the common case and awkward for the customization case).  I'm working on an improvement that would make things look like:

```java
Stetho.initializeWithDefaults();
```

-or-

```java
Stetho.initialize(Stetho.newInitializerBuilder()
    .enableDumpapp(new MyCustomDumpappPluginsProvider())
    .enableWebKitInspector(new MyCustomWebKitInspectorProvider())
    .build();

static class MyCustomDumpappPluginsProvider extends DefaultDumpappPluginsProvider {
  @Override
  public void addModules(Collection<DumperPlugin> modules) {
    modules.add(new MyExtraPlugin());
  }

  @Override
  public void replaceModules(Collection<DumperPlugin> modules) {
    // replaces the existing one due to a conflict in the name
    modules.add(new MyFilesPlugin());
  }

  @Override
  public Set<String> removeModules() {
    return Collections.singleton("crash"); // remove the crash plugin; testers are trigger happy!
  }
}

static class MyCustomWebKitInspectorProvider extends DefaultWebKitInspectorProvider {
  @Override
  public void replaceModules(Collection<ChromeDevtoolsDomain> modules) {
    // automatically detects that this trumps the original Network module
    modules.add(new Network(myConfiguration));
  }
}
```

All of the above override methods are _optional_ and only provided if you want to carry out the action specified.


Note that the API could certainly be improved further without the need to create your own provider subclasses but this is actually being done for performance reasons to effectively "lazy" the majority of the actual initialization work until such time as the first stetho peer connects.  This matters so that Stetho doesn't create any noticable drag on cold start times for your debug builds, which would obviously be quite frustrating for developers.

**Comment by jasta** [comment]
Cc @rightparen who I think will probably have some thoughts on this as well.

**Comment by rightparen** [comment]
Good call on adding a default initializer.

For customization, I like the idea of making it easier to modify defaults.  Consider returning defaults in a Map to provide add/replace/remove semantics:

    Stetho.initialize(Stetho.newInitializerBuilder()
        .enableDumpapp(createPluginsProvider())
        .enableWebKitInspector(createInspectorModulesProvider(context))
        .build());

    private static DumpappPluginsProvider createPluginsProvider() {
      return new DumpappPluginsProvider {
        @Override
        public Iterable<DumperPlugin> get() {
          Map<String, DumperPlugin> plugins = Stetho.defaultDumperPlugins();

          // remove existing plugin
          plugins.remove(CrashDumperPlugin.NAME);

          // add new plugin
          plugins.put(MyExtraPlugin.NAME, new MyExtraPlugin());

          // replace existing plugin
          plugins.put(FilesDumperPlugin.NAME, new MyFilesPlugin());

          return plugins.values();
        }
      };
    }

    private static InspectorModulesProvider createInspectorModulesProvider(
        final Context context) {
      return new InspectorModulesProvider {
        @Override
        public Iterable<ChromeDevtoolsDomain> get() {
          Map<String, ChromeDevtoolsDomain> modules = Stetho.defaultInspectorModules();

          // remove existing module
          modules.remove(HeapProfiler.NAME);

          // add new module
          modules.put(MyExtraModule.NAME, new MyExtraModule());

          // replace existing module using customized DatabaseFilesProvider
          modules.put(
              Database.NAME,
              new Database(context, new MyDatabaseFilesProvider(context)));

          return modules.values();
        }
      };
    }

This seems simpler than adding a new set of callbacks.

**Comment by jasta** [comment]
@rightparen I'm not so sure this is the right approach.  It means at a minimum that the `Stetho.default*Modules()` method call must construct instances of the modules that may just simply be replaced before they are installed/used.  This seems unnecessarily sloppy.  My thought was to divide this into two steps: let the user provide their set of custom modules, then merge it with the defaults.  I was thinking I'd still provide the base modules provider interfaces, but have a special Default one that acts as a helper assuming that you do want at least one of the default modules.

I'll try to code up what I was imaging so we can throw stones at something more concrete.
