### ISSUE TITLE
Browse and edit all the apps internal files

### ISSUE THREAD

**Issue by snowpong** [facebook/stetho#202]
It would be great to some point be able to browse and edit not only the database and preferences, but also the apps internal files.

I don't know where in chrome://inspect it would go though. Resources / Local storage?

Anyways - here is a short dumpapp plugin that list all files for an app. Enjoy.

https://gist.github.com/snowpong/cdf53a3f69023b27c16e

**Comment by jasta** [comment]
I've wanted to do this for quite some time but couldn't figure out a way to expose it in the main UI given the protocol we have to implement.  They have some concept of files but it's really crude for our purposes and then of course binary files just wouldn't work at all.

Instead I've been thinking about a dumpapp plugin to zip/tar up all data in the app storage and unpack it on the developer's machine.  This plugin could go in reverse as well, taking those files and uploading them back into place.  This would be kind of like adb shell am backup but faster and more flexible (for instance, backup doesn't support cache files).

Thoughts?  Any chance you have cycles to expand your diff to something like that and do a PR?

**Comment by snowpong** [comment]
So basically a sort of "dropbox" auto-sync feature. Sounds cool.

I don't have a lot of freetime on hand, so it won't come from me atm :)

**Comment by jasta** [comment]
Oops, forgot to reference this issue in my PR: #207.  Hopefully this does what you're looking for :)

Note that I haven't implemented the "upload" support yet so you can't apply your changes easily.  Hopefully we can get that working soon :)
