### ISSUE TITLE
Chrome doesn't see my device

### ISSUE THREAD

**Issue by IgorGanapolsky** [facebook/stetho#213]
Hi,
I followed all the steps for setting up Stetho.  But my Chrome just flashes 
>Pending authentication: please accept debugging session on the device.

Please advise.

**Comment by jasta** [comment]
Another user is reporting this issue internally.  I am wondering if a recent Chrome update broke some stuff.  Does Chrome see another Chrome instance on this device?  If not, it may be worth either downgrading or looking at chrome logs or chrome issues to see anyone else complaining.

**Comment by IgorGanapolsky** [comment]
I am experiencing this issue on both - regular Chrome as well as Canary
Chrome.  So I don't know if its a version issue, or how I can downgrade.

**Comment by jasta** [comment]
I don't know how to downgrade Chrome for you, but for Linux it's a simple matter of installing the google-chrome-stable package and running that instead.

Again, if Chrome can another Chrome for Android instance on your phone then it is possible they changed the protocol on us somehow and we will need to either file a bug about this or implement whatever new wizardry they've done.  The Chrome team tends to work on this part of the code quite a lot.

**Comment by IgorGanapolsky** [comment]
I am having this problem on all Chrome-based browsers.  For example: Melstrom browser from Bittorrent.

**Comment by auchenberg** [comment]
Can you try run a `adb shell cat /proc/net/unix | grep devtools_remote`` on that specific device? This could query for the relevant services including chrome+stetho.

Chrome used to look for ``devtools_remote``, but that might have changed.

**Comment by ypresto** [comment]
I have same issue and nothing shown up with `adb shell cat /proc/net/unix | grep devtools_remote`.

**Comment by IgorGanapolsky** [comment]
@auchenberg When I run your command, I get
> 00000000: 00000002 00000000 00010000 0001 01 1980698 @stetho_com.eazyigz.RussiaMediaSearch_devtools_remote

What does it mean?

**Comment by auchenberg** [comment]
@IgorGanapolsky That't means a Stetho process with the name of ``@stetho_com.eazyigz.RussiaMediaSearch_devtools_remote`` is running on the device, and should be discoverable by Chrome. 

I'd conclude that this issue most likely is caused by a change in Chrome's discoverability of devices. Which specific version of Chrome are you running, on which platform?

**Comment by IgorGanapolsky** [comment]
@auchenberg I tried on Version 45.0.2449.0 canary (64-bit) and Version 43.0.2357.130 m.

**Comment by jasta** [comment]
I did some spelunking on this and I believe this bug only repros with
genymotion.  Can you confirm this is a real device or standard emulator?

Also, can you confirm that it toggles this error message on and off? That's
what I saw reproing on a coworkers machine.

**Comment by IgorGanapolsky** [comment]
It is indeed a real device - Samsung Galaxy s4, running latest CM nightly.
This problem does not happen on my OnePlus One device.

**Comment by tsuharesu** [comment]
Same problem here. Chrome shows the device intermittently... 
Moto X 2014 - Chrome Version 43.0.2357.93
Windows 8.1 Chrome Version 43.0.2357.132 m

**Comment by tsuharesu** [comment]
Got it working by changing the connection from MTP to PTP

**Comment by IgorGanapolsky** [comment]
@tsuharesu How do you do that on Galaxy S4?

**Comment by changetip** [comment]
Hi @tsuharesu, @IgorGanapolsky sent you a Bitcoin tip worth 3,603 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/869612)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by jasta** [comment]
Interesting, I was seeing this repro on a genymotion emulator previously which I presume doesn't have any meaningful settings around USB connection mode.  I wonder what's going on here with Chrome...

**Comment by IgorGanapolsky** [comment]
Like I said: it happens only on one device.  So I don't know if its a
Chrome issue per se.

**Comment by jasta** [comment]
I suspect Chrome because the issue suddenly appeared for a large number of users with a number of different scenarios/manifestations (genymotion not regular emulator, one physical device over another with no OTAs, changing device USB settings fixes it, etc).  It's hard to believe that suddenly a bunch of phones out there just broke.

It's also impossible that it's a Stetho issue because I confirmed that indeed the entire device is not visible and cannot even seen native Chrome for Android instances.  It's simply a matter of Chrome failing to communicate with the device/emulator instance at all.

**Comment by IgorGanapolsky** [comment]
Actually, the device DOES appear intermittently (for 2 seconds) on Chrome
device panel, but then flashes away continuously (on and off).  So there is
some kind of security issue.

**Comment by tsuharesu** [comment]
Using Chrome Canary helped... for some time. Now everything is strange again.

**Comment by jasta** [comment]
@IgorGanapolsky right I'm aware that the issue is intermittent, but do you see how it is highly unlikely to be Stetho and/or your specific device?  So many users suddenly began seeing this issue with no updates to Stetho and no changes to their device.  Chrome, meanwhile, is updated regularly.

I'm very interested in understanding what's going on, but I'm pursuing it from the angle that Chrome and/or something it depends on to connect to ADB is the issue.

**Comment by chandsie** [comment]
Hello!
I'm having this issue as well. My device shows up intermittently (flashing on and off every second or so) in chrome://inspect. Hitting inspect when it is visible opens up the inspector but nothing can be viewed (presumably because the device is no longer visible).

Here are details to hopefully help dig into what's going awry:
Physical Device: Nexus 5/ Android 5.1.1
Chrome: Google Chrome Version 43.0.2357.134 (64-bit) for Mac OS X Yosemite 10.10.4

Running `adb shell cat /proc/net/unix | grep devtools_remote` shows that a stetho process is running.

**Comment by felipecsl** [comment]
this is most likely a chrome issue, i've been seeing this frequently lately as well. Started a few weeks ago

**Comment by IgorGanapolsky** [comment]
The solution was already reported - go to your device settings and use PTP
for usb connection.

**Comment by ubuntudroid** [comment]
Using PTP doesn't help here.
Chrome: 43.0.2357.134 (64-bit)
Phone: Nexus 5 running stock Android 5.1.1
Stetho: 1.1.1

**Comment by jasta** [comment]
@IgorGanapolsky I don't think the PTP issue is the full story here.  As I said, I've seen users reproing this on Genymotion which doesn't even connect via USB.  My best guess is some kind of race condition in Chrome itself.  I haven't yet reported the issue to them upstream however (being lazy, sorry *grin*)

**Comment by IgorGanapolsky** [comment]
@JoshGuilfoyle Sounds plausible.  However, switching to PTP is the only
thing that fixed it on my Galaxy S4.  No other solutions I tried (different
Chrome variations, etc) worked.

**Comment by jkane001** [comment]
I've been having this problem for a couple weeks now, and though switching to PTP worked for a minute, it's back to broken for me. For what it's worth, there's an issue logged against Chromium for it.

I think it would be great if everyone who's got the issue went to the [Chromium issue](https://code.google.com/p/chromium/issues/detail?id=512150) and starred it - we need to increase visibility into the issue!

**Comment by longinoa** [comment]
Thanks @jkane001 so does running `adb kill-server` temporarily fix this for you?

**Comment by jkane001** [comment]
@longinoa You know, I missed where someone mentioned that, but I bet it will - cause last night, I restarted my machine, and upon restart, it worked fine, until I started up Android Studio and built to my device. Once I did that, the flashing was back. So I think I'm in agreement with that person - this seems to be an ADB/Chrome incompatibility.

**Comment by dpa99c** [comment]
I was able to resolve this issue by downgrading the Android SDK tools and platform tools.

It became a problem for me when I upgraded Android SDK tools from 24.2.0 to 24.3.4 and platform-tools from 21 to 23.

Using Chrome (44.0.2403.133) when connecting Samsung Galaxy S4, suddenly started getting the intermittent behaviour described above.

I downgraded SDK tools back to 24.2.0 and platform-tools back to 21 and issue went away.

Can only assume it's a problem between new version of SDK tools and Chrome.

**Comment by coreform** [comment]
Looks like it's a case of either Android Studio seeing the device OR chrome/Stetho, but not both.

Unchecking 'enable ADB integration' in Android Studio is the neatest way to switch between the two possibilities, it seems.

**Comment by longinoa** [comment]
Okay this looks to be an issue w/ chrome and adb. 

Im going to go ahead and close this out, but you should take @jkane001 's suggestion and star the https://code.google.com/p/chromium/issues/detail?id=512150

**Comment by santhosh77h** [comment]
I started noticing this today... not sure what changed. and i tried to click that blinking device only but it started working i don't know whats going inside chrome.

**Comment by jasta** [comment]
@santhosh77h this issue was confirmed fix upstream by Chrome.  What version are you running?  Also, if you can, try unstable or beta to confirm that it still exists.  It's entirely possible they broke it again, but without further evidence I doubt it :)

**Comment by santhosh77h** [comment]
@jasta chrome Version 40.0.2214.111

**Comment by jasta** [comment]
Yeah that's the old buggy version.  Upgrade to the latest stable and it should fix it.

**Comment by santhosh77h** [comment]
okay i will let you know

**Comment by andela-kakpobome** [comment]
A year later, reboot of Mac and phone did nothing to resolve.

**Comment by andela-kakpobome** [comment]
Steps [here](https://stackoverflow.com/questions/31638582/android-adb-devices-unauthorized) helped me resolve.

```
I removed the following files from the ~/.android folder:

adbkey
adbkey.pub
I disabled and enabled ADB within device and now it works...
```

**Comment by daisuke0925m** [comment]
Sharing my steps so far, in case it helps others:

- At first `adb` wasn’t installed (`command not found`).  
  After installing via `brew install android-platform-tools`, Chrome started detecting the device more reliably.
- Reset USB debugging authorization (OFF→ON, “Revoke USB debugging authorizations”) 

Now it’s “almost stable,” but not 100% consistent yet.
