### ISSUE TITLE
Nothing show in Chrome DevTool.

### ISSUE THREAD

**Issue by MarkMjw** [facebook/stetho#217]
Chrome find device and app but inspection does not show any thing.
my Chrome version:  43.0.2357.132 (64-bit)
os: OS X 10.10.4
like this:
![d63381c3-5088-4af6-a6f0-873286428ff0](https://cloud.githubusercontent.com/assets/4126838/8561798/282f961c-255d-11e5-8782-807103c6cfe4.jpg)

**Comment by jasta** [comment]
This is caused by builds that use proguard but don't include rules to keep Stetho.  See https://github.com/facebook/stetho/wiki/FAQ, first question (sorry can't link to the header sections for some reason)

**Comment by MarkMjw** [comment]
Thanks, it's solved.
