### ISSUE TITLE
Column = null doesn't work (SQL)

### ISSUE THREAD

**Issue by black-snow** [facebook/stetho#224]
Querying null fields doesn't work with 

```SQL
SELECT * FROM table WHERE column = NULL;
```

**Comment by jasta** [comment]
Your sqlite syntax is wrong.  You're looking for column IS NULL.  Note that
your query is sent directly to sqlite so if it doesn't work or has syntax
errors it's unlikely to be stetho's issue.

**Comment by black-snow** [comment]
Ah, thanks
