### ISSUE TITLE
enableWebKitInspector API is incorrect

### ISSUE THREAD

**Issue by paulirish** [facebook/stetho#25]
There isn't a webkit inspector any longer.  

The Chrome DevTools live inside Blink and Blink was forked from WebKit two years ago. They are now extremely different.

**Comment by jasta** [comment]
Good to know.  Part way through development we started to realize the storied history in part and have some conflicts in the APIs/internals.  We'll be working to clean those up moving forward.  I'll leave this task open since its covering a major API.

**Comment by paulirish** [comment]
In terms of vocabulary this is the layout: 

* Chrome DevTools - name of the total product
* (Chrome) DevTools frontend - the webapp that provides the UI
* [Chrome Debugger Protocol](https://developer.chrome.com/devtools/docs/debugger-protocol) - well, you know.

**Comment by paulirish** [comment]
> I'll leave this task open since its covering a major API. 

yeah seems good. Can I open a PR to update the readme?

**Comment by jasta** [comment]
Of course, but do note that we have a CLA process that you must complete before we can merge.

**Comment by jasta** [comment]
@paulirish, any chance you could take a look at #13?  We've been having trouble lately with Chrome 40 breaking things in seemingly undocumented ways which seems very much related to the fork you mentioned.

**Comment by paulirish** [comment]
@jasta yeah i'll jump in over at #13. Technically this is unrelated to the fork. :)

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jasta** [comment]
This has been addressed in part by a new much simpler API which doesn't even specify the web kit inspector commonly.  See #234.
