### ISSUE TITLE
Is there has a better way  support protobufs?

### ISSUE THREAD

**Issue by lincleejun** [facebook/stetho#250]
Hi there!
I was use stetho for a while, but right now I working on stetho support protobuf, I didn't find a good way to support it, can any one help me?

My currently solution is rewrite a NetWork implements ChromeDevtoolsDomain, as same as stetho provided except response body, translate the body from Protobuf to Json . 

Is there a better way to solve this problem??

PS: In the beginning, I wrote a class extends stetho Network, but It didn't work, finnally I found out that in the [MethodDispatcher](https://github.com/facebook/stetho/blob/master/stetho/src/main/java/com/facebook/stetho/inspector/MethodDispatcher.java) it use class name as RPC called method name. 
Why not provide a getName in the ChromeDevtoolsDomain or something like that???

**Comment by jasta** [comment]
We have a PR right now building this.  It implements a "pretty printer"
concept which lets you install filters to interpret your binary data.  It
is intended to be extended by your application using the pretty printer
registry provided.

Right now this support targets only response payloads but the intention is
to expand it to requests as well.  A new PR just landed which begins that
work as well by adding a request filter to both stetho-okhttp and
stetho-urlconnection.

**Comment by lincleejun** [comment]
OK, thanks guys.

**Comment by jasta** [comment]
For reference, here is that PR: #219

**Comment by Caij** [comment]
@lincleejun Have you found a good solution?
