### ISSUE TITLE
Ability to add Stetho protocol/domain library extensions

### ISSUE THREAD

**Issue by sromku** [facebook/stetho#258]
Chrome protocol calls are designed to be coupled to `ChromeDevtoolsDomain` implementations and it is impossible to add more functionality to existing domains/modules. 

For example there is a `Database` class that has methods: `getDatabaseTableNames` and `executeSQL`.
Because of `MethodDispatcher` implementation and [dispatch table map](https://github.com/facebook/stetho/blob/master/stetho%2Fsrc%2Fmain%2Fjava%2Fcom%2Ffacebook%2Fstetho%2Finspector%2FMethodDispatcher.java#L39), the calls will look for specific class name and for method as [defined in protocol](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/devtools/protocol.json&l=1668). This is very coupled which is right for low level protocol wrapping. 

But, this limits the ability to extend and add new functionality to already covered domains. Check this screenshot. I had to make some not healthy implementations to make it work. The **Web SQL** tab shows all Android and custom made content providers. Since Android content providers like *Calendar, Contacts, ...* aren't accessible through raw sqlite database, I had to create new `Database` class (same name) with more extended functionality and override Stetho Database class in dispatch table map. 

![Screenshot](https://github.com/EverythingMe/easy-content-providers/wiki/images/stetho-providers.png)
This is the repo with new stetho extension: https://github.com/EverythingMe/easy-content-providers

Here, I would like to suggest ability to add external extensions to Stetho library and discuss it :) 

I can suggest some PR for better discussion. For example adding some `ChromeDevtoolsDomainListener` and then be able to add functionality to existing domains. Or suggest another level of abstraction in addition to `ChromeDevtoolsDomain` that will support extensions. 

What do you think?

**Comment by longinoa** [comment]
@sromku What do you men to extend the protocol? Are you also modifying the implementation of the Chrome Dev tools in chrome?

I think adding content providers would be pretty awesome but Im just not sure I follow the protocol extension.

**Comment by sromku** [comment]
@longinoa What I mean is not by modifying the protocol itself, but adding an option to the Stetho lib. When Chrome invokes protocol method like `getDatabaseTableNames`, `Database` class is the only one to get this call. I suggest, to add an option of registering listeners and be notified about Chrome calls.

I will create PR with some suggested solution/direction and provide some new API snippets. This will help me to explain it better :)

**Comment by auchenberg** [comment]
As a initiator of [RemoteDebug](http://remotedebug.org), who has spent quite a significant amount of time looking into remote debugging protocols, I'd suggest that you went with a somewhat prefixed extension of the protocol, first so we (as in the community), easily can identify the extensions you added to the protocol, but also to reduce the possibility for collisions

If I remember correctly, [node-inspector](https://github.com/node-inspector/node-inspector) has also extended the protocol to add new functionality.

**Comment by sromku** [comment]
@auchenberg In the current protocol version - ['Database' domain definition](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/devtools/protocol.json&l=1620) is enough for working with android content providers. Because, eventually these providers are just another layer of structured set of data, like databases. 

If I understood you correctly you suggest to extend the protocol itself. Which means also backing it with UI components in Chrome Dev Tool. This will be an overkill for such feature. Or, you mean something else?

**Comment by auchenberg** [comment]
@sromku No, I thought you wanted to extend the protocol under the ``Database``-domain to add support for Android content providers, but that doesn't sound like the case. 

If you eventually are going to extend the protocol, I recommend the above.

**Comment by longinoa** [comment]
@sromku I haven't had a chance to really dig into this yet, and @jasta is on vacation. 

A PR may make this a bit easier to parse but for the specific case of implementing a bridge between the Database tab and a content provider seems like it wouldnt want to extend the protocol, but just register itself as a table provider?

**Comment by sromku** [comment]
@longinoa please check the suggested PR: https://github.com/facebook/stetho/pull/264

Please check 2 commits

1. The first commit is the suggestion of how to make the Database domain extendable. 
The idea is that Database class can contain many DatabasePeers and delegate the query to the correct one. 
2. In the second commit you will find example of how Calendar content provider (`CalendarProviderDatabasePeer`) extends the `DatabasePeer` and is added as extension to the `Database` class.

**Comment by jasta** [comment]
This has been merged.
