### ISSUE TITLE
JSON formatting of request/response body

### ISSUE THREAD

**Issue by rodrigo-alvarez-chaoticmoon** [facebook/stetho#259]
It would be really helpful if the request and response body in the Network traffic view could be formatted in traditional JSON fashion.

**Comment by longinoa** [comment]
@rodrigo-alvarez-chaoticmoon This isnt something that stetho controls. This is code that we get from the Developer tools built into chrome. The preview tab has the response json expanded out into an object structure that is clickable. The problem with requests is that traditional web requests dont traditionally include a ton of data going TO the server so they didnt add the pretty formatting. 

If you are interested in changing the format of the json output, you can take a look at one of the features that we currently have in development (not yet released but committed #219).
