### ISSUE TITLE
Stetho filling logs with "unsupported request received: GET /devtools/browser"

### ISSUE THREAD

**Issue by BlueHayes** [facebook/stetho#262]
If I open a tab at `chrome://inspect`, my application starts logging the following every second:

```
08-21 14:47:00.437    5655-6693/com.***.*** W/stetho﹕ Unsupported request received: GET /devtools/browser HTTP/1.1
```

This is a bit annoying because in Android Studio, the log keeps jumping down to the bottom each second whilst trying to review errors or other debugging logs. So I resort to closing `chrome://inspect`, only to have to open the tab again to connect to the app once re-deployed.

Chrome version: 44.0.2403.155

Thanks

**Comment by auchenberg** [comment]
Looks to be related to this change in Chrome.

https://chromium.googlesource.com/chromium/src/+/f30ed78e50a7569001f37845601b8a71fcefd4a4%5E%21/

**Comment by jasta** [comment]
Well now this is very interesting indeed.  It looks like they're making it possible to provide our own custom UI to support this protocol but still integrate within Chrome.  This could be very powerful for us down the road...

**Comment by jasta** [comment]
I can't seem to reproduce this on Chrome beta: 46.0.2490.13.  Is there something special you had to do to turn this on?

**Comment by BlueHayes** [comment]
I'm seeing it in version 45.0.2454.85 but not in 47.0.2506.0 canary.

However, I've also just realised this doesn't happen when deploying the app to my test device, it's only happening in the emulator (Nexus 5 x86 API 22).

**Comment by BlueHayes** [comment]
Ok, I've figured out what's causing the issue. You need to have port forwarding enabled at `chrome://inspect` (any Chrome version). Disabling port forwarding resolves the issue.
