### ISSUE TITLE
Leakcanary like no-op version for release builds

### ISSUE THREAD

**Issue by aashrairavooru** [facebook/stetho#263]
Stetho is awesome,but i don't always want to put it in my release builds for various reasons, currently doing something like this requires maintaining two Application classes in different build variants which can be painful and buggy. A simple no-op version of negligible size will be awesome

**Comment by burntcookie90** [comment]
right now, i'm just using a simple `StethoInjector` like this:

```java
public class StethoInjector {
    public static void injectStetho(final Application application) {
        Stetho.initialize(
                Stetho.newInitializerBuilder(application)
                      .enableDumpapp(
                              Stetho.defaultDumperPluginsProvider(application))
                      .enableWebKitInspector(
                              Stetho.defaultInspectorModulesProvider(application))
                      .build());
    }

    public static Interceptor getStethoNetworkInterceptor() {
        return new StethoInterceptor();
    }

    public static void log(final Console.MessageLevel logLevel, final Console.MessageSource other, final String msg) {
        CLog.writeToConsole(
                logLevel,
                Console.MessageSource.OTHER,
                msg);
    }
}
```

that injects into debug, and then no-ops in QA and PROD

**Comment by longinoa** [comment]
You should take a look at #16 (which is likely what you are doing with build variants). I think one of the bigger reasons to keep this as a compile time optimization is removing all of the methods in proguard.
