### ISSUE TITLE
initialization issue

### ISSUE THREAD

**Issue by caoxuwen** [facebook/stetho#27]
when initialize stetho with my app, i always get this error:

java.lang.VerifyError: com/facebook/stetho/dumpapp/Dumper
            at com.facebook.stetho.Stetho$Initializer.getRegistry(Stetho.java:142)
            at com.facebook.stetho.server.LocalSocketHttpServer.createService(LocalSocketHttpServer.java:232)
            at com.facebook.stetho.server.LocalSocketHttpServer.listenOnAddress(LocalSocketHttpServer.java:158)
            at com.facebook.stetho.server.LocalSocketHttpServer.run(LocalSocketHttpServer.java:134)
            at com.facebook.stetho.Stetho$1.run(Stetho.java:80)

the initialization code i'm using:
    Stetho.initialize(
        Stetho.newInitializerBuilder(this)
            .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
            .enableWebKitInspector(Stetho.defaultInspectorModulesProvider(this))
            .build());

is there something i'm missing with the setting/build? i looked at the dumper code, not sure what could be causing this.

**Comment by jasta** [comment]
Are you using the Maven/Gradle dependency or the JAR?  Things have been a little crazy on launch day and we might have made a mistake in one of the integration paths.

**Comment by caoxuwen** [comment]
just using the JAR

**Comment by jasta** [comment]
Yes, we made a mistake bundling the commons-cli dependency.  To fix your problem quickly, add this JAR as well: http://central.maven.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.jar

We'll fix it for everyone else shortly by creating a fatjar.  Sorry about that!

**Comment by jasta** [comment]
Oops, shouldn't have closed yet :)

**Comment by caoxuwen** [comment]
awesome, thanks

**Comment by jasta** [comment]
Can you try: https://github.com/facebook/stetho/releases/download/v1.0.0/stetho-1.0.0-fatjar.jar?  This should work for you.

**Comment by caoxuwen** [comment]
yes it works now

**Comment by jasta** [comment]
Swung the link at http://facebook.github.io/stetho/ over to the new fatjar.  Thanks for reporting!

**Comment by adnan-SM** [comment]
Same issue here with Gradle.

**Comment by jasta** [comment]
@adnan-SM I just retested the instructions using Gradle and everything is working fine.  Are you sure you're not seeing a different symptom?  Gradle should be automatically bundling the `commons-cli` library for you that was causing problems in the JAR release.
