### ISSUE TITLE
Device appears offline on the devtools

### ISSUE THREAD

**Issue by lynfogeek** [facebook/stetho#271]
My Genymotion VM is correctly connected to `adb` and runs my app, but the connection with the chrome dev tools is switching from authenticated to offline every few seconds.

Note that if I click on `inspect` the "session" will be opened and it works properly.

Configuration:
- Genymotion 2.5 
- Stetho 1.1.1
- Chrome 44.0.2403.157 (64-bit)
- Fedora 20

![stetho_offline](https://cloud.githubusercontent.com/assets/1833455/9679531/a1c14f10-52ef-11e5-9938-87331a0eb839.png)

**Comment by jasta** [comment]
This is a bug in Chrome itself and I believe has been fixed upstream, though the fix is not yet present in stable.  It's a race condition and it's unclear how it can be mitigated or worked around though some folks have proposed solutions in #213.
