### ISSUE TITLE
View Hierarchy doesn't get refresh

### ISSUE THREAD

**Issue by marcos-dogonahorse** [facebook/stetho#276]
When you look at the "View Hierarchy" under the elements tab and your switch Activity in the app, the "View Hierarchy" doesn't get updated. Switching tabs in the chrome developer tools doesn't refresh it either.

**Comment by rickbrew** [comment]
A new activity won't be auto-expanded so it can be easy to miss. Is that possibly what's happening? 

If that isn't the case, does the new Activity show up if you close the Chrome window and re-attach via `chrome://flags` ?

**Comment by jasta** [comment]
We've made major changes to how this part of Stetho works in 1.2.0.  Can you check out the new release to see if this issue remains?
