### ISSUE TITLE
inspect show nothing

### ISSUE THREAD

**Issue by pinguo-fandong** [facebook/stetho#277]
I found my device,but chrome shows nothing

**Comment by pinguo-fandong** [comment]
![Uploading QQ图片20150909134840.png…]()

**Comment by pinguo-fandong** [comment]
![3](https://cloud.githubusercontent.com/assets/7663243/9754403/77acde6e-56fb-11e5-87e9-c8f02f667c5e.jpg)
os:windows 8.1
chrome:45.0.2454.85 m(32)

**Comment by jasta** [comment]
This can occur if you either a) don't have Internet access on your laptop/PC, or b) you have used proguard on your app and it obfuscated the class names Stetho depended on for reflection purposes.  There's a section in the FAQ (https://github.com/facebook/stetho/wiki/FAQ) about this problem, specifically showing which proguard rules are necessary if you wish to use proguard on your debug builds.

**Comment by jasta** [comment]
Feel free to re-open if I'm wrong :)

**Comment by pinguo-fandong** [comment]
I fact,it works on my mac pro,still not in Windows system!

**Comment by pinguo-fandong** [comment]
Thank you all,I forgot connecting the network!

**Comment by AllenVork** [comment]
![stetho](https://cloud.githubusercontent.com/assets/5970517/26662492/ccae2cae-46b6-11e7-8056-0d77413042f3.png) My network is connected and my app is not proguarded. I still got nothing. My chromium is 56.0.2924.76 Built on Ubuntu , running on Ubuntu 16.04 (64-bit).
