### ISSUE TITLE
Inspector !!!

### ISSUE THREAD

**Issue by hienandroid** [facebook/stetho#283]
Hi !!!
I feel very wonderful about stetho and i have a feature. When i click item on listview stetho return results (time to get, json...) but i have image on every item in listview (image url from server - using picasso to load image) and i want to know time to get image from server every item listview. Currently, i just know about time to get data. If i know time to load video in my application. (get video from server's url). Please help me.

**Comment by jasta** [comment]
@hienandroid I don't think I am following your question.  If you want custom debugging of some property of your app you probably want to use Stetho to build a `dumpapp` plugin and instrument your code that way.  Stetho's main networking and elements tree UI is really just there to show you what's already occurred (or in flight for networking) and not provide additional debug options beyond just presenting the data.  `dumpapp` on the other hand is intended for instrumentation and custom analysis of specific systems so you can better reason about issues.

**Comment by hienandroid** [comment]
Thanks. But i want to show details information from server. When i get infor from server (i get json data from server and parse data afer display infor but in my data i have image url and display load image from server) and stetho networking just have time to get data json but not time to load image url from server). i want to know details time to get image from url

**Comment by jasta** [comment]
The time to fetch is displayed in Stetho.  If you look at the graph to the right of the requests you will see timing information.  Is this what you're interested in?

**Comment by hienandroid** [comment]
That's right, but it's just have timing information about json to get from
server. I want to know about timing to display image from server. Example:
i have a  button when i click button i get data json from server and
display infor from server in listview. (Important: each item in json data
from server have image url). After listview display infor from server (item
in listview have a imageview to display image). When i click button to get
data from server, stetho just display timing json infor from server, it'
not display details timing to get url from server to display in imageview.
Thanks so much.

**Comment by longinoa** [comment]
Do you see your image fetch requests show up at all? IE is your image 
fetching library hooked up to stetho. If you are using a third party 
library (glide/picasso/fresco) you will need to initialize your image 
library to work with stetho.

**Comment by jasta** [comment]
Closing assuming this is an issue with configuration of your image fetching library.  Please reopen if I'm wrong.
