### ISSUE TITLE
Picasso and exoplayer (media player)

### ISSUE THREAD

**Issue by hienandroid** [facebook/stetho#290]
I have a video app. I want to know timing about my app (timing load image and video). I using picasso to load image. When i install stetho for my app. I can't see timing to load image. Help me to setup stetho for picasso and media player to display time to load infor. Thanks so much.

**Comment by jasta** [comment]
For exoplayer, I know of no way you can intercept this data.  I haven't looked into it closely, but I suspect all you can do is sniff out network bytes using an approach like the one in https://github.com/facebook/network-connection-class.

For Picasso, you need to teach it about Stetho.  This can be done one of two ways:

1) If you use Picasso 2.5+ and OkHttp, you can do the easy thing recommended by Stetho:

```java
class MyOkHttpHolder {
  OkHttpClient sInstance;

  static {
    OkHttpClient client = ...;
    client.networkInterceptors().add(new StethoInterceptor());
  }

  OkHttpClient get() {
    return sInstance;
  }
}

new Picasso.Builder(...).downloader(new OkHttpDownloader(MyOkHttpHolder.get())).build();
```

2) Provide a custom network stack wrapper to Picasso which Stetho is aware of:

```java
new Picasso.Builder(...)
    .downloader(new MyStethoDownloader())
    .build();
```

You will have to code up `MyStethoDownloader`.  If you use `HttpURLConnection`, you can follow some of the example set by https://github.com/facebook/stetho/tree/master/stetho-sample but you are at least in some part on your own to adapt the concepts.
