### ISSUE TITLE
Adding Dialogs to descriptors (not DialogFragment)

### ISSUE THREAD

**Issue by pyricau** [facebook/stetho#295]
As far as I can tell, Stetho supports displaying `DialogFragments` in the Elements tab, but it doesn't support plain old dialogs, which I use.

I need to be able to add more Windows (the dialogs ones) to what Stetho is collecting. I thought you'd have implemented this for ChatHead already, so I might have missed something, let me know if that's the case.

In the meantime... Here's my dirty hack:

```
public class MyActivity extends Activity {

  @Override public Window getWindow() {
    if (!BuildConfig.DEBUG || !switchWindowToDialogForStetho) {
      return super.getWindow();
    }
    Window dialogWindow = mainPathContainer.getDialogWindowForDebug();

    if (dialogWindow == null) {
      return super.getWindow();
    }

    StackTraceElement[] stackTrace = new RuntimeException().getStackTrace();

    if (stackTrace[1].getClassName()
        .equals("com.facebook.stetho.inspector.elements.android.ActivityDescriptor")) {
      return dialogWindow;
    }

    return super.getWindow();
  }
}
```

**Comment by rickbrew** [comment]
Your analysis is correct :) `Dialog` is supported but *only* if it's attached to a `DialogFragment`. This was intentional, partly because we didn't know if anyone was using `Dialog` without `DialogFragment` ... and now we know!

**Comment by pyricau** [comment]
Fragments of any kind [are evil](https://corner.squareup.com/2014/10/advocating-against-android-fragments.html), over engineered and buggy ;) .

But surely, you'd love to be able to display those Messenger chat heads in Stetho. It'd be nice to add a hook to provide additional windows at any time.

**Comment by rickbrew** [comment]
I believe this will involve `ActivityDescriptor` reaching into the private details of `Activity` via reflection: the list of dialogs is maintained in a `SparseArray<Activity.ManagedDialog>`.

Get the list, enumerate it, exclude anything associated with a `DialogFragment`, and emit.

**Comment by rickbrew** [comment]
Okay check out #296 and see if it works for you.

**Comment by pyricau** [comment]
I'm sorry but that won't work for me.

Managed dialogs are deprecated, and a bad way to deal with dialogs.

When you do "new AlertDialog.Builder(context).show()", that dialog isn't stored anywhere. A dialog is essentially a wrapper around a child window of an activity window. 

See the source of `android.app.Dialog`, more specifically `android.app.Dialog#show`: `            mWindowManager.addView(mDecor, l);`

I check the latest sources, and WindowManager is implemented by [WindowManagerImpl](https://github.com/android/platform_frameworks_base/blob/master/core/java/android/view/WindowManagerImpl.java) which itself delegates to `WindowManagerGlobal`.

These can be accessed using reflection. If you're willing to go down that route (and it's probably fine since Stetho is a dev tool and already does reflection), below is an approach to list the root view of all windows. Let me know if you'd rather have me make a PR.

```
import android.os.Build;
import android.view.View;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Looks for all windows in the current process and finds the associated root view for each window.
 * Based on Expresso RootsOracle.
 */
public class WindowScanner {

  private static final String WINDOW_MANAGER_IMPL_CLASS = "android.view.WindowManagerImpl";
  private static final String WINDOW_MANAGER_GLOBAL_CLASS = "android.view.WindowManagerGlobal";
  private static final String VIEWS_FIELD = "mViews";
  private static final String GET_DEFAULT_IMPL = "getDefault";
  private static final String GET_GLOBAL_INSTANCE = "getInstance";

  private static final WindowScanner INSTANCE = new WindowScanner();

  public static WindowScanner getInstance() {
    return INSTANCE;
  }

  private boolean initialized;
  private Object windowManager;
  private Field viewsField;

  /**
   * Looks for all Root views
   */
  public synchronized List<View> findAllRootViews() {
    if (!initialized) {
      initialize();
    }

    if (windowManager == null || viewsField == null) {
      return Collections.emptyList();
    }

    try {
      if (Build.VERSION.SDK_INT < 19) {
        return Arrays.asList((View[]) viewsField.get(windowManager));
      } else {
        //noinspection unchecked
        return new ArrayList<View>((List<View>) viewsField.get(windowManager));
      }
    } catch (RuntimeException ignored) {
      return Collections.emptyList();
    } catch (IllegalAccessException ignored) {
      return Collections.emptyList();
    }
  }

  private void initialize() {
    initialized = true;
    String accessClass;
    String instanceMethod;
    if (Build.VERSION.SDK_INT > 16) {
      accessClass = WINDOW_MANAGER_GLOBAL_CLASS;
      instanceMethod = GET_GLOBAL_INSTANCE;
    } else {
      accessClass = WINDOW_MANAGER_IMPL_CLASS;
      instanceMethod = GET_DEFAULT_IMPL;
    }

    try {
      Class<?> clazz = Class.forName(accessClass);
      Method getMethod = clazz.getMethod(instanceMethod);
      windowManager = getMethod.invoke(null);
      viewsField = clazz.getDeclaredField(VIEWS_FIELD);
      viewsField.setAccessible(true);
    } catch (Exception ignored) {
    }
  }
}
```

**Comment by jasta** [comment]
Would you mind converting that snippet into a PR?  I think some cleanup is in order, but I'd very much like to have support for this.

**Comment by pyricau** [comment]
@jasta Done, see #325
