### ISSUE TITLE
Device is gets extremely slow when Inspector's window is opened and it uses databases

### ISSUE THREAD

**Issue by ClarkXP** [facebook/stetho#303]
I'm developing on Moto G sec gen (XT1068), Normally works smoothly, but when I'm debugging with Stetho, databases operations gets slow with the inspector open.

![captura de pantalla 2015-10-27 a las 16 36 55](https://cloud.githubusercontent.com/assets/3936769/10770269/6eec5c22-7cd1-11e5-9b02-f5fbfcbb531c.png)

0 to 6 = normal
10 to 25 = Chrome inspector open with Stetho.
The query gets only two items, with more items the experience is worst.

**Comment by jasta** [comment]
I'm not particularly sure why database operations would be so much slower, but we do know that UI performance suffers as we scan the view hierarchy every second looking for changes.  This is a naive implementation and should be optimized, but we just haven't quite found the cycles to get it done.  Ping @rickbrew :)

**Comment by jasta** [comment]
I now believe this is due to #323.  We really need to provide a solution for this somehow, it's just really unclear what form that will take yet.
