### ISSUE TITLE
error message for each log entry in the console using StethoTree

### ISSUE THREAD

**Issue by meierjan** [facebook/stetho#307]
After planting the `StethoTree` (I took it from your stetho-timber folder, just changed the package name and put it into my project) I get an error before each log entry.

The error looks like this:
```
There were X bytes that were not consumed while processing request Y
- LOG ENTRY HERE -
```

I am planting it like this in my application-class:
```
[...]
if (BuildConfig.DEBUG) {
            Stetho.initializeWithDefaults(this);
            Timber.plant(new Timber.DebugTree());
            Timber.plant(new StethoTree());
} [...]
```

Am I missing something or is this a bug?
(I used the issue-search and found nothing)

**Comment by jasta** [comment]
This error indicates that your networking layer is not reading all the bytes available from network input streams.  This would occur for instance if you were using OkHttp and did:

```java
Response response = client.newCall(request).execute();
response.body().byteStream().read(1);
```

Assuming, of course, that there was more than 1 byte to be read :)

This can often occur with JSON or image parsing layers that ignore "junk" at the end of the stream.  For instance, if you had the following reply "{}{}" and you parsed that as a single JSON object using JsonReader, you would not read the last two bytes ("{}").  Stetho would then report that 2 bytes were unread.  It is logged at debug level as it will still report this read to the DevTools UI.
