### ISSUE TITLE
depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by danielgomezrico** [facebook/stetho#315]
I want to use stetho with timber and okhttp so I used:

```
devCompile 'com.facebook.stetho:stetho-okhttp:1.2.0'
devCompile 'com.facebook.stetho:stetho-timber:1.2.0'
```

But I get:
`Warning:Module 'com.facebook.stetho:stetho-timber:1.2.0' depends on one or more Android Libraries but is a jar`

Why?

**Comment by jasta** [comment]
I think the warning is about the fact that stetho-timber doesn't ship as an aar but does itself depend on an aar.  FWIW, we ship stetho-timber as both a jar and aar for reasons that I don't fully understand (gradle is honestly so bizarre with respect to Maven uploads).  It should be a harmless warning, though I am interested in figuring out how to make sure Stetho ships exclusively as an aar.

**Comment by danielgomezrico** [comment]
:+1:
