### ISSUE TITLE
Device Offline: Pending authentication: please accept debugging session on the device

### ISSUE THREAD

**Issue by lalozhang** [facebook/stetho#316]
When I debug my application, it is shown that "Pending authentication: please accept debugging session on the device",but I can not find a debugging session on my screen.My android phone is Nexus6.

**Comment by jasta** [comment]
This was an old bug in Chrome fixed in v45 I believe.  If you are using an older version, try upgrading.  Otherwise, make sure that ./scripts/dumpapp works and can connect as well, verifying that ADB is indeed working properly.

**Comment by kumudamasanaik** [comment]
While inspecting my application in chrome  i am getting "Pending authentication: please accept debugging session on the device." in Redmi4. but i enabled developers option in Redmi4 but still i am getting this issue so suggest me anyone how to solve this.
