### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by tyronen** [facebook/stetho#318]
1. Add a link to GitHub in the top. The only link now is actually the releases link near the bottom of the page.
2. The phrase "See the stetho-sample project" should actually link to that code in GitHub.
3. You have to git-clone stetho to use dumpapp. Could it be made downloadable as a par instead?

**Comment by jasta** [comment]
Great feedback, thank you.

**Comment by jasta** [comment]
Re (3), we're trying to add it to pypi so `pip install stetho` will work.  See #508
