### ISSUE TITLE
App slows down during continious generating json for DOM inspector

### ISSUE THREAD

**Issue by stepango** [facebook/stetho#326]
In worse cases few second app freeze. 

As workaround I exclude DOM and CSS from InspectorModulesProvider. 

Probably DOM should be generated only when `Elements` tab are active in Chrome inspector.

**Comment by jasta** [comment]
See #323, we're interested in a solution but don't quite have one ready yet.  FWIW, we do try to make the Elements tab operate lazily, it's just that Chrome doesn't give us any clue as to when the tab is open / active.
