### ISSUE TITLE
okhttp3 support

### ISSUE THREAD

**Issue by AAverin** [facebook/stetho#327]
New version of okhttp have changed the way interceptors are added to the client.
When can we expect stetho update to support okhttp3?

**Comment by felipecsl** [comment]
This is being tracked by #324

**Comment by kamilwlf** [comment]
When you plan to fix it?

OkHttpClient okClient = new OkHttpClient.Builder()
                    .addNetworkInterceptor((Interceptor) new StethoInterceptor())
                    .build();

Caused by: java.lang.ClassCastException: com.facebook.stetho.okhttp.StethoInterceptor cannot be cast to okhttp3.Interceptor

I use compile 'com.squareup.okhttp3:okhttp:3.0.0-RC1'

**Comment by panzerdev** [comment]
This would really be an Important change! Also OkHttp 3.0 is final as of today.

**Comment by jakewilson801** [comment]
I totally agree with @panzerdev I'm dying to have this working with OkHttp3.0

**Comment by jasta** [comment]
Sorry folks, I was asleep at the wheel on this and will be cutting a release tomorrow to address this.  A new module will be added, `stetho-okhttp3` which will replace the current `stetho-okhttp`.

**Comment by jasta** [comment]
#324 is now closed, the milestone (https://github.com/facebook/stetho/milestones/1.3.0) now tracks the release.
