### ISSUE TITLE
Showcase screencasting feature on website

### ISSUE THREAD

**Issue by auchenberg** [facebook/stetho#336]
The screencasting feature landed quite a while ago, but isn't mentioned anywhere. 

Maybe a nice animated GIF or something could share the knowledge about this awesome feature?

**Comment by jasta** [comment]
I was hoping by now we'd have fancy things like mouse and keyboard support piped through :(

**Comment by auchenberg** [comment]
Yeah, so you want to wait until the full blown this is there?

**Comment by jasta** [comment]
Ideally, yes, though we shouldn't wait forever...

**Comment by jasta** [comment]
Let's take another look at this in a month or so.
