### ISSUE TITLE
Stetho support for Firefox Developer Tools

### ISSUE THREAD

**Issue by bkerensa** [facebook/stetho#35]
Would be nice if Stetho was built for Firefox the only open source browser out there or bake it into a Firefox Addon

**Comment by jasta** [comment]
Actually you can use Firefox.  If you download the chrome-devtools UI (which is open source: https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/devtools/front_end/&q=protocol.json&sq=package:chromium&type=cs), you can host it locally using a simple webserver like `python -m SimpleHTTPServer 8000`.  This is actually how we used to do things before we implemented `chrome://inspect`.  The main advantage to the latter is that we don't need to ship the frontend HTML/JS with Stetho.

**Comment by bejibx** [comment]
Hi, is this more precise instruction somewhere for those who not so familiar with all this stuff?

**Comment by anksite** [comment]
Yes...  How i can downlad that stuff from your given link..

**Comment by spipau** [comment]
The provided link is not working any more, I get the following message:

> Could not load src/third_party/WebKit/Source/devtools/front_end/: Could not resolve path src/third_party/WebKit/Source/devtools/front_end.

Firefox support would be awesome! ❤️

**Comment by Inc0n** [comment]
It would be great, if an additional browser to be installed just for the devtool purpose.

**Comment by Inc0n** [comment]
I found out about `devtools-backend`, but I am unsure of how this may be used to work with stetho.
