### ISSUE TITLE
Application frame drop

### ISSUE THREAD

**Issue by Woren** [facebook/stetho#350]
I was using version 1.1.0 (everything was great) and now I upgraded to 1.3.0. But when I open Chrome inspection for my application - during changing of activities I get massive frame drop (almost to zero) for few seconds. Sometimes I also get "Application is not responding" dialog. There is error log with many messages containing (generated every few ms):

> com.facebook.stetho.inspector.elements.android.DialogFragmentDescriptor.getChildren() emitted a null child at position 0 for element SomeMyFragment

I'm initializing Stetho with: 

`Stetho.initializeWithDefaults(this);`
or with
`Stetho.initialize(
                    Stetho.newInitializerBuilder(ctx)
                            .enableDumpapp(Stetho.defaultDumperPluginsProvider(ctx))
                            .enableWebKitInspector(Stetho.defaultInspectorModulesProvider(ctx))
                            .build());`

I get same result also for version 1.2.0. I have to notice that all my fragments inherits from DialogFragment (support v4) and Activities from AppCompatActivity (support v7). I'm also using network interceptor for okHttp but it was disabled during my tests.

In the meantime - is there any way how to disable Elements section for Inspection? My guess is that this is using this sort of problems. Thanks.

**Comment by rickbrew** [comment]
I checked in some fixes that we're planning to push out in a 1.3.1 update soon. One of the fixes prevents the Elements tab from significantly over-sending tree updates to Chrome. I saw times for `Document.updateTree()` drop massively on my test devices.

**Comment by Woren** [comment]
Thanks for reply and those fixes. Is there any way how to disable Elements tab if it doesn't help in the worst case scenario?

**Comment by jasta** [comment]
@Woren the problem really exists upstream.  They don't offer a way to lazily enable the Elements tab only when you click on it which prevents us from doing a lot of important optimizations.  We have not yet filed this issue with Chrome however but it may be time to do that if @rickbrew's fixes are insufficient.

**Comment by rickbrew** [comment]
We defer as much initialization until the first call from Chrome to `DOM.getDocument()` ... but IIRC that was being called right away. It's worth investigating more of course.

**Comment by jasta** [comment]
Closing for now as it is assumed @rickbrew's fixes are sufficient to ease the pain for now.  Please re-open if you disagree after you try out 1.3.1 and we'll look into further optimizations and filing issues upstream to get this conditionally enabled.

**Comment by matthewmichihara** [comment]
Thanks for the updates guys. Just to confirm, is there no way to disable the Element tree functionality in Stetho? I don't find myself using it so I'd like to turn it off if possible.

**Comment by longinoa** [comment]
Currently there is no way to do this.

The protocol that dev tools uses supports the feature however the version stetho is targeting does not ever send disable.
