### ISSUE TITLE
how to run stetho with retrofit 2.0.0-beta4 and okhttp?

### ISSUE THREAD

**Issue by kamilwlf** [facebook/stetho#352]
how to run stetho with retrofit 2.0.0-beta4 and okhttp?
my okhttp:
OkHttpClient okClient = new OkHttpClient.Builder()
                    .addNetworkInterceptor(new StethoInterceptor())
                    .build();
retrofit:
Retrofit client = new Retrofit.Builder()
                    .baseUrl(baseUrl)
                     ???
                    .addConverter(String.class, new ToStringConverter())
                    .addConverterFactory(GsonConverterFactory.create())
                    .build();

**Comment by jasta** [comment]
I'm not sure what your question actually is.  This sample code appears generally correct to me and would seemingly integrate with Stetho just fine?

**Comment by kamilwlf** [comment]
I checked again and it works, thank you for confirmation!
