### ISSUE TITLE
Stetho makes my app noticably laggier when upgrading from 1.1.1 to both 1.2 and 1.3

### ISSUE THREAD

**Issue by matthewmichihara** [facebook/stetho#356]
I'm having a hard time debugging why though.

During scrolls, after upgrading I constantly see things like --
```
Choreographer  
    I  Skipped 107 frames!  The application may be doing too much work on its main thread.
    I  Skipped 79 frames!  The application may be doing too much work on its main thread.
```

where previously on 1.1.1 frames weren't skipped. I'd like to dig into this more, any pointers on where to look or what information I can provide that would be helpful?

We're using stetho with okhttp `com.facebook.stetho:stetho-okhttp` with the `StethoInterceptor` okhttp interceptor. Our `Application#onCreate` has the following --

```{java}
Stetho.initialize(
                Stetho.newInitializerBuilder(this)
                        .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
                        .enableWebKitInspector(Stetho.defaultInspectorModulesProvider(this))
                        .build());
```

**Comment by matthewmichihara** [comment]
This only happens while I have the Chrome network inspector open. When I'm just using the app without Chrome, it runs fine.

**Comment by jasta** [comment]
I believe this is #326 (and many other related issues).  The underlying issue was partially addressed by @rickbrew through several optimizations.  We'll be cutting a release today (1.3.1) which will contain the optimizations.

**Comment by matthewmichihara** [comment]
that was so fast, thanks!
