### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by taosimple** [facebook/stetho#362]
added `debugCompile 'com.facebook.stetho:stetho:1.3.1'` and run , build fail print as below : 
```
:jianShu:transformClassesWithJarMergingForDebug FAILED
Error:Execution failed for task ':jianShu:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: javax/annotation/PropertyKey.class
Information:BUILD FAILED
```

**Comment by jasta** [comment]
This doesn't seem right to me.  I would bet that you've got another artifact which incorrectly bundles jsr-305 and Stetho uses jsr-305 which causes debugCompile to pull in its transitive dependencies then causing a conflict with an improper artifact you already have.  Search around your app classpath looking for a jar or a set of sources which redundantly include jsr-305 and remove it from them.

**Comment by leesunghyun** [comment]
```
debugCompile ('com.facebook.stetho:stetho:1.3.1') {
        exclude module: 'jsr305'
    }
```
