### ISSUE TITLE
Documentation incorrect: With OkHttp3 you cannot add the interceptor by mutating the networkInterceptors() list. 

### ISSUE THREAD

**Issue by kypeli** [facebook/stetho#363]
The Stetho website says that you can add the Stetho network interceptor with a line such as 
`client.networkInterceptors().add(new StethoInterceptor());`

However, this is not true because OkHttp3 is immutable and you have to use the Builder approach to add the interceptor. You will get the following exception if doing so:
  ```
java.lang.UnsupportedOperationException
      at java.util.Collections$UnmodifiableCollection.add(Collections.java:928)
```

This worked for me
```
new OkHttpClient.Builder()
    .addNetworkInterceptor(new StethoInterceptor())
    .build();
```

Here are my dependencies. 
```
 compile 'com.squareup.okhttp3:okhttp:3.2.0'
 compile 'com.facebook.stetho:stetho:1.3.1'
 compile 'com.facebook.stetho:stetho-okhttp3:1.3.1'
```

**Comment by jasta** [comment]
My fault, forgot to update the website documentation for okhttp3.

**Comment by jasta** [comment]
...and then I failed to fix it :)

**Comment by jasta** [comment]
Oops, no I didn't.  It correctly calls out the different API choices between okhttp2 and 3 now :)
