### ISSUE TITLE
dumpapp "Multiple stetho-enabled processes"

### ISSUE THREAD

**Issue by antonkrasov** [facebook/stetho#37]
Hi Guys,

Here is another issue. When I'm trying to execute 
```
./dumpapp prefs print
```
I see:
```
Multiple stetho-enabled processes available:
	com.mypackage
	com.mypackage
Use -p <process> to select one
```

It just display 2 equals packages, so when I try to specify package with -p com.mypackage it doesn't work.

What I did is open adb shell, and executed:

```
shell@klte:/ $ ps | grep com.mypackage
u0_a216   10774 259   965576 54048 ffffffff 00000000 S com.mypackage
```

So, I'm not really sure what's wrong.

P.S. com.mypackage is just replacement for my real package :)

Please let me know if you will need more details from me. 
I really want to use this project, it should save so lot's of time :)

**Comment by hegazy** [comment]
The issue of the same package duplicate happening with me and I'm sure that I'm using only one process, but when I use the `-p` option it works just fine.

**Comment by jasta** [comment]
I noticed this myself recently.  Can you try running `adb shell cat /proc/net/unix | grep @stetho`?  This is where the information comes from to populate that list of process names that you see.

**Comment by antonkrasov** [comment]
I see:
```
00000000: 00000002 00000000 00010000 0001 01 745200 @stetho_com_<MY_PACKAGE>_devtools_remote
00000000: 00000002 00000000 00000000 0001 03 759612 @stetho_com_<MY_PACKAGE>_devtools_remote
00000000: 00000002 00000000 00000000 0001 03 759608 @stetho_com_<MY_PACKAGE>_devtools_remote
```

**Comment by jasta** [comment]
That is weird indeed.  If you kill your process (`adb shell run-as com.mypackage kill pid`), what does the `... | grep @stetho` line show?  Just trying to make sure things are being cleaned up as expected.

**Comment by antonkrasov** [comment]
Ok, so after ```adb shell run-as com.mypackage kill pid``` all works fine. But after couple of reinstalls the app, and one uninstall then install I see multiple processes again.

**Comment by jasta** [comment]
Lol, *facepalm*.  Entries show up in this list even for when they are client connections to that server socket.  In other words, if you open `chrome://inspect` and inspect your process you should start seeing multiple entries show up.

This should be fixed by filtering out the results that are not in the bound socket state or just removing duplicates.  I'll do a PR :)

**Comment by antonkrasov** [comment]
I see, nice :)
