### ISSUE TITLE
App crash at launch with stetho-js-rhino

### ISSUE THREAD

**Issue by chethann** [facebook/stetho#372]
App crashes at launch after including stetho-js-rhino. Works fine with plain stetho and okHttp. Logcat says `Caused by: java.lang.NoClassDefFoundError: org.mozilla.javascript.tools.debugger.treetable.JTreeTable`. 

I have  `multiDexEnabled true`. Is the library not supported with multidex? 

Please help. Thank you!

**Comment by jasta** [comment]
Hmm, it should work just fine with multi dex enabled.  It's entirely possible that your proguard config has stripped out rhino but left stetho alone (or you manually added the necessary stetho rules to keep it).  Can you check whether this class actually exists in your APK file (dexdump and grep on the various classes*.dex files in the APK would do the trick).

**Comment by jasta** [comment]
Closed due to a lack of follow-up
