### ISSUE TITLE
Failed  to Remove Stetho

### ISSUE THREAD

**Issue by biaomingzhong** [facebook/stetho#374]
I am using build types on android studio 2.0 like #16 

I am using stetho without okhttp just like this 

`debugCompile 'com.facebook.stetho:stetho:1.3.1'`

Everytime I try to release I get an error transformClassesAndResourcesWithProguardForRelease

And I used the "find in path" tools to find out that there was no use of Stetho

But when I modified build.gradle like this 

`compile 'com.facebook.stetho:stetho:1.3.1'`

It is good.

**Comment by jasta** [comment]
Can you possibly provide a repro case so I can pull locally and try to figure out what's going on?  The sample app uses debugCompile and works properly.  There may be something unique to your gradle configuration that's causing issues but it's hard to guess at that without something concrete to look at.
