### ISSUE TITLE
crashed  when click "Inspect" in chrome://inspect.

### ISSUE THREAD

**Issue by aso210** [facebook/stetho#378]
`04-25 16:59:30.160 E/AndroidRuntime( 3918): FATAL EXCEPTION: StethoWorker-main-22
04-25 16:59:30.160 E/AndroidRuntime( 3918): java.lang.NoClassDefFoundError: javax/annotation/Nonnull
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at java.lang.reflect.Method.isAnnotationPresent(Native Method)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at java.lang.reflect.Method.isAnnotationPresent(Method.java:284)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.inspector.MethodDispatcher.isDevtoolsMethod(MethodDispatcher.java:136)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.inspector.MethodDispatcher.buildDispatchTable(MethodDispatcher.java:116)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.inspector.MethodDispatcher.findMethodDispatcher(MethodDispatcher.java:53)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:60)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
04-25 16:59:30.160 E/AndroidRuntime( 3918): Caused by: java.lang.ClassNotFoundException: javax.annotation.Nonnull
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
04-25 16:59:30.160 E/AndroidRuntime( 3918): 	... 22 more`

**Comment by jasta** [comment]
This smells like a proguard configuration issue.  See https://github.com/facebook/stetho/wiki/FAQ#nothing-is-shown-in-chrome-devtools-and-i-see-many-method-not-implemented-messages-in-logcat.  Please re-open if I'm wrong :)
