### ISSUE TITLE
Support Volley usage

### ISSUE THREAD

**Issue by davidgarsan** [facebook/stetho#38]
How can I use Stetho while using Volley as a networking library?

**Comment by jasta** [comment]
Our thought was that Volley would be supported by extending the appropriate `HttpStack` implementation.  `HurlStack` for instance is not final and in particular `HurlStack#openConnection` is suitable for `StethoURLConnectionManager#preConnect`, with `HurlStack#performRequest` being good for `postConnect` and `interpretResponseStream`.  I have not personally tested this, but from my read of the Volley code I think it should work perfectly.
