### ISSUE TITLE
Ubuntu Chrome Nexus 6 Inspect not available

### ISSUE THREAD

**Issue by dmfrey** [facebook/stetho#380]
I have setup Stetho in my app. However, when I go to chrome//inspect, I can see a list of devices, but I cannot perform any actions on them. There are no inspect buttons, like others, have reported.

System Details:
Ubuntu 15.04
Chrome Version 50.0.2661.86 (64-bit)
Nexus 6, Android 6.0.1 (April 2, 2016)

Do I need to do any extra setup for Android Studio or ADB in order to make this work on Linux?

**Comment by dmfrey** [comment]
So this was totally my fault. After I rebooted my laptop it was working then.

**Comment by bogdanRada** [comment]
hello, can you tell me how you managed to solve it? i have same problem :(

**Comment by GabrielDelepine** [comment]
@bogdanRada Did you enable the "USB Debugging" on your android device?

source : https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

**Comment by bogdanRada** [comment]
Forgot to mention that i solved it. Thank You very much
