### ISSUE TITLE
The Response is all the same

### ISSUE THREAD

**Issue by xiaohuhu** [facebook/stetho#383]
When I wait for all the request complete,then click the response,the **response** is the same.All the response is for the last request

![u4o667xeh4jz jh 4m 865](https://cloud.githubusercontent.com/assets/7322048/15114095/d317db52-162a-11e6-92c7-8c06af75d5b1.png)

If I click the response before the next request ,the response is right.

![hkhj 8tg3 x4zyih b 92](https://cloud.githubusercontent.com/assets/7322048/15114043/8c85974c-162a-11e6-940a-66a40feae5b3.png)

![_rc fthei l97rt u7tl 6](https://cloud.githubusercontent.com/assets/7322048/15114049/937468f8-162a-11e6-910f-88c324c2d32f.png)

I use 
    compile 'com.facebook.stetho:stetho:1.3.1'
    compile 'com.facebook.stetho:stetho-okhttp3:1.3.1'
    compile 'com.squareup.okhttp3:okhttp:3.2.0'

`Stetho.initializeWithDefaults(this);`
`  client = new OkHttpClient.Builder().addNetworkInterceptor(new StethoInterceptor()).build();`

**Comment by jasta** [comment]
Hmm, to try to debug this further you can take a look at the response files Stetho writes to your app directory (`/data/data/<yourpackage>/files/network-response-body-#`) to ensure that they are indeed unique and correspond roughly to the requests in order.  If these files show the same response, then the problem would be in StethoInterceptor.  To debug that, you could try adding your own interceptor before Stetho's that peaks at the contents just to make sure it is indeed unique.  If it isn't, the bug may well be in okhttp itself.  If it is, then we have to start trying to use the debugger in StethoInterceptor to figure out why it thinks the response are non-unique.

**Comment by xiaohuhu** [comment]
@jasta Thanks,I found the reason.
In my code, every request new a OkHttpClient  
` OkHttpClient a = new OkHttpClient.Builder().addNetworkInterceptor(new StethoInterceptor()).build();`
Therefore the requestId is always 0 ,and the new network-response-body will replace the previous files.
Thanks for help me!

**Comment by jasta** [comment]
FWIW, that was very inefficient for your application as well as it meant each request had to create a new connection.  I suspect your app's performance on slow networks has improved greatly :)
