### ISSUE TITLE
Cannot resolve method MyDumperPlugin()

### ISSUE THREAD

**Issue by abdulgaffar291** [facebook/stetho#386]
While initialzing the stetho - dumber plugin 

`Stetho.initialize(Stetho.newInitializerBuilder(context).enableDumpapp(new DumperPluginsProvider(){
                        @Override
                        public Iterable<DumperPlugin> get() {
                            return new Stetho.DefaultDumperPluginsBuilder(context)
                                    .provide(new MyDumperPlugin())
                                    .finish();
                        }
                    }).enableWebKitInspector(Stetho.defaultInspectorModulesProvider(context))
                    .build());`

**Comment by jasta** [comment]
Hmm, it looks like you simply have to create your MyDumperPlugin class.  See existing dumper plugins for help getting started (my preference is `SharedPreferencesDumperPlugin`)

**Comment by abbasalill** [comment]
Hi there is no class myDumperplugin
