### ISSUE TITLE
Database viewer not available

### ISSUE THREAD

**Issue by wideawake** [facebook/stetho#40]
Hi guys,

does the plugin need a rooted phone to let the database viewer open the .db file?

Thanks

**Comment by jasta** [comment]
It shouldn't, no.  In fact, one of our main design goals was to not require root or special privileges to operate.

Can you explain a little bit about what isn't working?

Also, give the stetho-sample app a try (`gradle installDebug` in the stetho project root) to see if the inspection works there.  Clicking the "APOD" button will cause a database to be created.  Note that there is currently a bug where databases that are created after you first open the inspector UI will never appear in the list.  Just closing and re-opening the inspector will fix it.

**Comment by wideawake** [comment]
It's working now. I don't know what was going wrong before since the database was already created when the app was launched and show in the inspector.

Thanks anyway

**Comment by semenoh** [comment]
In my case it does not show database if .db file is on sd-card (`/mnt/sdcard/`)

**Comment by jasta** [comment]
@semenoh interesting use case, we hadn't actually considered that.  It is theoretically possible to configure this through the `Database` module but I think you've exposed a possible gap in our API surface area.  Specifically, it's very awkward to have to provide a custom `InspectorModulesProvider` and manually override the `Database` object with your own custom configured version.  I think we need to think through this a little bit more.

**Comment by jasta** [comment]
@semenoh does #91 solve your issue?

**Comment by wwfighting** [comment]
@jasta I have a problem about Web SQL, I can only see the name of database but not the table and the data. and if I execute database statement, it has an error 'unknow error (code 14): could not open database'

**Comment by longinoa** [comment]
@wwfighting This is related to the 1.4.0 release that we cut last week, I am investigating it now in #431

**Comment by wwfighting** [comment]
@longinoa oh,I see. waiting for your new version and thanks for your reply

**Comment by hram** [comment]
same issue on 1.4.0 
after update on 1.4.0  i cant see db tables
after downgrate to 1.3.1 works fine

**Comment by mriyas** [comment]
I had the same problem since my port was busy with some other task. Check your port is available
