### ISSUE TITLE
Cannot view more than 250 records in sqlite table due to MAX_EXECUTE_RESULTS = 250

### ISSUE THREAD

**Issue by developer1011** [facebook/stetho#404]
Currently there is no way to see more than 250 records in sqlite database tables using Stetho. Because of below setting in Database.java. Can you please explain is there a way for pagination or alternative to see all records in sqlite table using Stetho

/**
   * The protocol doesn't offer an efficient means of pagination or anything like that so
   * we'll just cap the result list to some arbitrarily large number that I think folks will
   * actually need in practice.
   * <p>
   * Note that when this limit is exceeded, a dummy row will be introduced that indicates
   * truncation occurred.
   */
  private static final int MAX_EXECUTE_RESULTS = 250;

**Comment by longinoa** [comment]
There is no way to see all records in stetho if you have more then 250 rows. There is no pagination in the protocol.

You could possibly sort and then select specific ranges.

**Comment by abiemann** [comment]
Stetho should have a setter to let the dev set the number of rows.
If the dev didn't set it, then assuming 250 is appropriate.

**Comment by ashikazeez** [comment]
There is no way to see all records in stetho if you have more then 250 rows. set LMIT and OFFSET for more data

**Comment by jasta** [comment]
Note also that you can actually use stetho to download your database files and view them with tools like http://sqliteman.yarpen.cz/.  This is what I do actually using ./scripts/dumpapp and the files plugin.

**Comment by ninadmg** [comment]
@jasta how do you download database files using stetho?

**Comment by jasta** [comment]
See: ./scripts/dumpapp files
