### ISSUE TITLE
Incorrect Rhino initialization

### ISSUE THREAD

**Issue by paour** [facebook/stetho#405]
In [`JsRuntimeReplFactoryBuilder.JsRuntimeReplFactoryBuilder`](https://github.com/facebook/stetho/blob/master/stetho-js-rhino/src/main/java/com/facebook/stetho/rhino/JsRuntimeReplFactoryBuilder.java#L87), the default package that is added is the app's packageName, but that may not be the actual Java package name, it's  really just the applicationId. This may cause an exception at launch.

In any case, the [`importPackages`](https://github.com/facebook/stetho/blob/master/stetho-js-rhino/src/main/java/com/facebook/stetho/rhino/JsRuntimeReplFactoryBuilder.java#L204) method doesn't work for the application's packages, since it doesn't prefix the package name with `Packages`, [which is required](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Scripting_Java#External_Packages_and_Classes) to import non-default-java packages.

**Comment by paour** [comment]
`importClass` has a similar issue.

**Comment by potyl** [comment]
I tried the following in my app:
```
importPackage(android.text)
TextUtils.htmlEncode("hello & world");
```
And I got:
> "hello &amp; world"

Can you show an example how this doesn't work?

I also tried with a package from our app (not the default package) and I was able to call `name()` on an enum.
