### ISSUE TITLE
build error release apk when use stetho-okhttp:1.3.1

### ISSUE THREAD

**Issue by onion4** [facebook/stetho#407]
When I debug it's ok,but when I build use gradle assembleRelease ,it build failed with an exception.
Error log:
Uncaught translation error: com.android.dx.cf.code.SimException: com.android.dx.rop.cst.CstInterfaceMethodRef cannot be cast to com.android.dx.rop.cst.CstMethodRef

I guess it must be cause about proguardFiles,I need help,Tks.

**Comment by longinoa** [comment]
this sounds like something that is not related to stetho, can you try removing stetho temporarily and trying your release build.

**Comment by onion4** [comment]
@longinoa  I have try to remove stetho and build release apk.    It build success.

**Comment by longinoa** [comment]
What version of google play services is your app targeting?

**Comment by onion4** [comment]
The project don't have google play services.

**Comment by jackcsk** [comment]
I can confirm that I experience the same issue:
```
:ModuleName:transformClassesWithDexForPlay_storeRelease
AGPBI: {"kind":"error","text":"Uncaught translation error: com.android.dx.cf.code.SimException: com.android.dx.rop.cst.CstInterfaceMethodRef cannot be cast to com.android.dx.rop.cst.CstMethodRef","sources":[{}]}
AGPBI: {"kind":"error","text":"1 error; aborting","sources":[{}]}

```

**Comment by jackcsk** [comment]
Here's the stetho version I use:
```
    compile 'com.facebook.stetho:stetho:1.4.1'
    compile 'com.facebook.stetho:stetho-okhttp:1.4.1'
```
and I am building on Android Studio 2.3.1
