### ISSUE TITLE
Inspect doesn't work

### ISSUE THREAD

**Issue by AllenVork** [facebook/stetho#408]
I click the "Inspect" button and a new **empty** chrome tab appears.My chrome is up to date and I don't know what's wrong.

**Comment by AllenVork** [comment]
the empty screen doesn't even has the menu "Elements..."

**Comment by zergtmn** [comment]
Can confirm. Inspect doesn't work in Chrome 52.

**Comment by longinoa** [comment]
Can you try inspecting a native chrome browser on your phone? Also anything in logcat or developer console in chrome?

**Comment by AllenVork** [comment]
I got it. My ubuntu is 12.04, only support chromium of 37.0.2062.120 Ubuntu 12.04 (281580) (64-bit).How can I do with it.I don't wanna update my ubuntu for it may cause a lot of problem.

**Comment by longinoa** [comment]
This would be a chromium question...

**Comment by xiemeilong** [comment]
I have the same issue on Ubuntu 14.04 and chrome 55.0.

**Comment by xiemeilong** [comment]
The reson is GFW. Some resource is blacked in china.

**Comment by heronghua** [comment]
I came up with the same questions.It worked fine several days ago,the same chrome the same stetho library,but it happened this empty issue when I try to debug last time.
