### ISSUE TITLE
Webview can use Stetho?

### ISSUE THREAD

**Issue by gdky005** [facebook/stetho#412]
I want debugging H5, and review webview performance。 If it can use,  I think this is a very interesting thing。 

If can't use the native，use third party webview, debugging H5, and intercepting the data.I want to see the length of the access network.

**Comment by longinoa** [comment]
You would need to have the `WebView` instrumented. Thats not something stetho can do automatically.

If you are using `OkHttp` in the rest of your app you may look at approach similar to https://artemzin.com/blog/use-okhttp-to-load-resources-for-webview/
