### ISSUE TITLE
error - Not implemented: Profiler.setSamplingInterval

### ISSUE THREAD

**Issue by eikaramba** [facebook/stetho#42]
i included stetho and stetho okhttp via gradle and calling
```
Stetho.initialize(
                    Stetho.newInitializerBuilder(this)
                            .enableDumpapp(
                                    Stetho.defaultDumperPluginsProvider(this))
                            .enableWebKitInspector(
                                    Stetho.defaultInspectorModulesProvider(this))
                            .build());
```
inside my Application class, however after opening chrome and clicking inspect on the corrsponding item, i get a new window with
```
Not implemented: Profiler.setSamplingInterval
```
in the console

**Comment by jasta** [comment]
It's common to see a few `Not implemented` messages stream by.  It represents specific JSON-RPC methods as part of the Chrome Debugger protocol that we don't understand/implement yet.

Is there something that's actually not working as a result or is this just a concern about the warnings?

**Comment by eikaramba** [comment]
sry for late answer. Actually on my very first try, nothing worked and the error was shown. However, when i tested it again it now works and the error is gone.

**Comment by joshzana** [comment]
I am seeing this exact thing with my app. The stetho sample in the repo works fine, but with the OP's initialize() code, and the gradle dependency, all I get is the following in devtools console:

  Not implemented: Profiler.setSamplingInterval

And the following in logcat: 

I/stetho﹕ Listening on @stetho_com.dropbox.android_devtools_remote
D/ChromeDevtoolsServer﹕ onOpen
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Page.canScreencast
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Page.canEmulate
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Worker.canInspectWorkers
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Console.setTracingBasedTimeline
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Console.enable
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Network.enable
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Page.enable
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Page.getResourceTree
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Debugger.enable
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Debugger.setPauseOnExceptions
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Debugger.setAsyncCallStackDepth
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Debugger.skipStackFrames
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Runtime.enable
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: DOM.enable
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: CSS.enable
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Timeline.enable
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Database.enable
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: DOMStorage.enable
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Profiler.enable
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Profiler.setSamplingInterval
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: IndexedDB.enable
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: DOM.getDocument
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Worker.setAutoconnectToWorkers
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Inspector.enable
D/ChromeDevtoolsServer﹕ Method not implemented: Not implemented: Page.setShowViewportSizeOnResize

With the stetho sample app, I don't see the DevTools console error.

Any ideas?

**Comment by jasta** [comment]
You're using proguard obfuscation and/or shrinking.  If the latter, odds are you're doing this for the Dalvik method limit issues, so your best solution is to keep/keepnames `com.facebook.stetho.inspector.protocol.module.*`.

I intended to put up a wiki for this but haven't gotten around to it yet.  Some info can be found here:

https://github.com/facebook/stetho/issues/80#issuecomment-77955530

**Comment by joshzana** [comment]
Sigh.  It's always Proguard.
This is the fix:
-keep class com.facebook.stetho.** {*;}

Thanks!

**Comment by thuytrinh** [comment]
:+1:

**Comment by genius15** [comment]
helpful ,I met the same problem
