### ISSUE TITLE
Default stetho artifact includes compiled R class

### ISSUE THREAD

**Issue by alenz316** [facebook/stetho#422]
The default artifact is a jar that includes a compiled R class. Using this R class to reference resources would be incorrect, as it needs to be generated at compile time to have the correct ids.

One possible solution is to change the default artifact to an aar, then the R file will be generated correctly. 

Example gradle dependency to reproduce the issue:
 `debugCompile 'com.facebook.stetho:stetho:1.3.1'`

**Comment by longinoa** [comment]
You can use the aar version by doing the following:
```
debugCompile ('com.facebook.stetho:stetho:1.3.1:@aar') {
  transitive = true
}
```

We may need to look at moving to having aar be the default - but the timeframe on this is likely going to be a bit off as @jasta is off the grid.
