### ISSUE TITLE
Stetho's OkHttp3 interceptor logs incomplete request

### ISSUE THREAD

**Issue by paour** [facebook/stetho#423]
If an application is using other OkHttp3 interceptors besides Stetho's, the network log shows the state of the request at the point Stetho is located at within the interceptor chain, not the request as it was actually sent over the wire.

I don't have a PR to offer, but conceptually, [this block](https://github.com/facebook/stetho/blob/master/stetho-okhttp3/src/main/java/com/facebook/stetho/okhttp3/StethoInterceptor.java#L53) should use not the `request` object it's getting from the `chain` (it will be superseded by the next interceptor in the chain), but from `response.getRequest()`, which contains the final Request as it bubbles back up the chain of interceptors after the request has been submitted.

The fact that we would need to wait for the response to come back (or not) before calling `NetworkEventReporterImpl#requestWillBeSent`, so the timing might be off.

**Comment by longinoa** [comment]
We ran into a similar problem with this internally, and looked at a few different solutions... 
1) provide a separate interface to add interceptors.
2) use something similar to what you propose above
3) attach the `StethoInterceptor` as the last interceptor by convention. 

Ultimately we ended up going with 3. The basic assumption is that most consumers will have some sort of utility library that provides them with an `OkHttpClient` they will just start using and dont tend to add more interceptors as this is more of an application level concept

**Comment by paour** [comment]
Option 3 above would need to be documented. The [Quick-start documentation](http://facebook.github.io/stetho/#enable-network-inspection) is in need of changes, in any case: the first example (`client.networkInterceptors().add(new StethoInterceptor());`) is incorrect, since `networkInterceptors` is an immutable list…

Could you expand on option 1? I'm not sure I understand…

**Comment by longinoa** [comment]
So basically 1 would be stetho providing a builder interface for okhttp rather than requiring you to call `addNetworkInterceptor` yourself. This is really not a good direction for stetho as we support multiple versions of okhttp and would have to rev the builder each time a new version came out. It looks like #426 is a good modification to the readme

**Comment by longinoa** [comment]
@paour  does #426 close this for you?

**Comment by paour** [comment]
Yes, thank you.
