### ISSUE TITLE
Network inspection not working with OkUrlFactory

### ISSUE THREAD

**Issue by bryanstern** [facebook/stetho#43]
If you are using OkHttp + Volley, you are likely using `OkUrlFactory` via a class like the one below. Unfortunately OkHttp's network interceptors do not support the OkUrlFactory.
https://github.com/square/okhttp/wiki/Interceptors#availability

```java
import com.android.volley.toolbox.HurlStack;
import com.squareup.okhttp.OkHttpClient;
import com.squareup.okhttp.OkUrlFactory;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;

/**
 * An {@link com.android.volley.toolbox.HttpStack HttpStack} implementation which
 * uses OkHttp as its transport.
 */
public class OkHttpStack extends HurlStack {
    private final OkUrlFactory mFactory;

    public OkHttpStack() {
        this(new OkHttpClient());
    }

    public OkHttpStack(OkHttpClient client) {
        if (client == null) {
            throw new NullPointerException("Client must not be null.");
        }
        mFactory = new OkUrlFactory(client);
    }

    @Override protected HttpURLConnection createConnection(URL url) throws IOException {
        return mFactory.open(url);
    }
}
```
Any ideas on an OkHttp UrlConnection friendly way of integrating Stetho?

**Comment by jasta** [comment]
@bryanstern you can integrate `HttpURLConnection` using `StethoURLConnectionManager`.  If you depend on `okhttp-urlconnection`, you can likely make this work pretty easily through subclassing `HurlStack`.  Note that you could probably more easily implement a better `OkHttpStack` than the one Google provided in Volley.  Basically all you'd need is:
```java
public HttpResponse performRequest(...) {
  Response okHttpResponse = mOkHttpClient.newCall(convertToCall(request, params)).execute();
  return convertToApacheResponse(okHttpResponse);
}
```

**Comment by bryanstern** [comment]
@jasta Thanks for suggestion. I ended up just implementing Volley's `HttpStack` interface and performing the request directly with OkHttp, doing away with `okhttp-urlconnection`. Once I feel more confident in the code, I'll post that gist up for those interested.

**Comment by bryanstern** [comment]
Here is the gist, just set the network interceptor on the OkHttpClient you pass in. https://gist.github.com/bryanstern/4e8f1cb5a8e14c202750

**Comment by jasta** [comment]
@bryanstern closing now that a solution exists.  I think if we're going to merge something in it's most likely to be from #51 or something like it which more generically supports Volley.
