### ISSUE TITLE
Network Inspection error

### ISSUE THREAD

**Issue by hram** [facebook/stetho#434]
When I choose network request and select "Preview"  or "Response" tab I can see the same response on all requests

**Comment by longinoa** [comment]
@hram what do you mean the same response? What http engine are you using?

**Comment by hram** [comment]
I'm using OkHttp:
`client.addNetworkInterceptor(new StethoInterceptor());`
And on all request I see the same response.

**Comment by longinoa** [comment]
Can you show a screen shot? I checked with one of my sample apps and am not seeing this.

**Comment by hram** [comment]
I'v this error only on one project, but now on this project API not works. A will send screenshot later.

**Comment by hram** [comment]
![r1](https://cloud.githubusercontent.com/assets/2150637/18644292/84915018-7eb1-11e6-84e5-990e13e722c7.PNG)
![r2](https://cloud.githubusercontent.com/assets/2150637/18644297/894b1756-7eb1-11e6-92a7-c1315921f434.PNG)
![r3](https://cloud.githubusercontent.com/assets/2150637/18644304/8dac2ee8-7eb1-11e6-8525-0f0dfa4f96d3.PNG)

in all 3 responses actually displaed last one

**Comment by hram** [comment]
in "Headers" tab data changed

**Comment by hram** [comment]
If last response has state 304 then all other requests has no preview available.

**Comment by jasta** [comment]
Is this still an issue?  It seemed like upstream okhttp would've fixed it by now but I admit I've lost all the context on this over a year later :(
