### ISSUE TITLE
Extend StethoInterceptor

### ISSUE THREAD

**Issue by hram** [facebook/stetho#438]
I have network layer with RPC
If I see network requests all of them have the same URL
How can I extend or modify StethoInterceptor to show on URL(Name/Path) column method name?
Or can I add new column?

**Comment by hram** [comment]
I think what I need is a new NetworkEventReporter
But how can I register new one?
NetworkEventReporter has one implementation and this one is single instance.

**Comment by jasta** [comment]
You don't extend NetworkEventReporter, you use the only existing implementation and just call the methods however you'd like to cause the chrome://inspect UI to do what you want.  See the differences between StethoInterceptor and StethoURLConnectionManagerImpl

**Comment by jasta** [comment]
Also note that if you want to customize StethoInterceptor, I'd recommend just copying it in your project.  It's not meant to be extensible and is really so small that copying it is not undesirable.  If you have general improvements you want to do though please do consider contributing back!
