### ISSUE TITLE
Update project files for Java 1.7 syntax support

### ISSUE THREAD

**Issue by rickbrew** [facebook/stetho#44]
I believe there's something we need to declare in gradle.properties and/or elsewhere. So let's figure that out.

**Comment by jasta** [comment]
Diamond syntax FTW!

**Comment by clemp6r** [comment]
You have to add the following in the android section of your build.gradle:

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
