### ISSUE TITLE
IOException: socket not created when running with Roboelectric Test

### ISSUE THREAD

**Issue by startthread** [facebook/stetho#440]
Getting this error:

`
java.io.IOException: socket not created
    at android.net.LocalSocketImpl.bind(LocalSocketImpl.java:303)
    at android.net.LocalServerSocket.__constructor__(LocalServerSocket.java:48)
    at android.net.LocalServerSocket.<init>(LocalServerSocket.java)
    at com.facebook.stetho.server.LocalSocketServer.bindToSocket(LocalSocketServer.java:142)
    at com.facebook.stetho.server.LocalSocketServer.listenOnAddress(LocalSocketServer.java:78)
    at com.facebook.stetho.server.LocalSocketServer.run(LocalSocketServer.java:74)
    at com.facebook.stetho.server.ServerManager$1.run(ServerManager.java:40)
`

I have roboelectric test RobolectricTestRunner calls Application's onCreate, and it initialize stetho.

`
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 23)
`

**Comment by PenguinBlues** [comment]
Experiencing this, too. Were you able to solve this issue?

**Comment by joncottrell** [comment]
This is still allowing the tests to run, but I just want to suppress it! It's very annoying!

**Comment by getsmp** [comment]
Have the same issue, too.

**Comment by Squeazer** [comment]
Same here, any fix for this?

**Comment by epetrenko** [comment]
I have the same issue here and use custom RobolectricTestRunner (which defines test version of my application class) to avoid such errors, which seems a little bit hacky solution.

Extending Application class:
```
public class MyApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        
        if (BuildConfig.DEBUG) {
            if (!isUnitTesting()) {
                Stetho.initializeWithDefaults(this);
            }
        }
    }

    protected boolean isUnitTesting() {
        return false;
    }
}
```

Then extending MyApplication and overriding isUnitTesting() method:
```
public class TestMyApplication extends MyApplication {

    @Override
    protected boolean isUnitTesting() {
        return true;
    }
}
```

And then extending RobolectricTestRunner:
```
public class MyRobolectricTestRunner extends RobolectricTestRunner {

    public MyRobolectricTestRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
    }

    @Override
    public Config getConfig(@NonNull Method method) {
        final Config defaultConfig = super.getConfig(method);
        return new Config.Implementation(
                defaultConfig.sdk(),
                defaultConfig.minSdk(),
                defaultConfig.maxSdk(),
                defaultConfig.manifest(),
                defaultConfig.qualifiers(),
                defaultConfig.packageName(),
                defaultConfig.abiSplit(),
                defaultConfig.resourceDir(),
                defaultConfig.assetDir(),
                defaultConfig.buildDir(),
                defaultConfig.shadows(),
                defaultConfig.instrumentedPackages(),
                TestMyApplication.class,  // <-- overriding application class for testing here
                defaultConfig.libraries(),
                defaultConfig.constants()
        );
    }
}
```

**Comment by jasta** [comment]
This looks like it's actually a Robolectric issue.  While the workarounds mentioned in this issue do seem like the right strategy short term, long term it would be beneficial to file this bug against Robolectric.  Specifically the issue appears to be that LocalSocket simply doesn't work properly on Robolectric and needs to be emulated.

My best guess as to why this would be would be that LocalSocket is a Linux-specific concept that Robolectric would need to port to run on other types of systems (OS X, Windows, etc) and that even for Linux it's possible Robolectric lacks the underlying C/C++ implementation to make LocalSocket work properly.  Stetho could probably detect this but it would be better and more consistent with Robolectric's long term vision to support this Android API properly so that tests can be written against it.

**Comment by kakopappa** [comment]
this is the solution I came up with. Works with robolectric 3

if (!isRoboUnitTest()) {
Stetho.initializeWithDefaults(this);
}

public static boolean isRoboUnitTest() {
return "robolectric".equals(Build.FINGERPRINT);
}

**Comment by zyc945** [comment]
it's works perfect

**Comment by kaershushu** [comment]
@kakopappa good works

**Comment by lichtstrahl** [comment]
https://github.com/facebook/stetho/issues/440#issuecomment-304174489
Cool! Yes, it works for me.
