### ISSUE TITLE
Add "releaseCompile" to gradle

### ISSUE THREAD

**Issue by shmoula** [facebook/stetho#442]
Is it possible to add some dummy library for release stage to gradle? Like Stetho has 2625 methods so something like in leakcanary may be useful - to enable Stetho just for debug stage like so:

`debugCompile 'com.facebook.stetho:stetho:1.4.1'`

`releaseCompile 'com.facebook.stetho:stetho-no-op:1.4.1'`

**Comment by shmoula** [comment]
Looks like there is simple solution for that - to create module and provide noop methods for yourself, [check this post](https://medium.com/@orhanobut/no-op-versions-for-dev-tools-b0a865934398#.3d3a9a6x3). Still hoping it will be added 'officially'.

**Comment by longinoa** [comment]
Yeah see #232 for a conversation on this.  Depending on what your configuration is it is possible to do this even without the post you linked to recommends. 

We would take a PR for this but don't really have cycles right now.

**Comment by longinoa** [comment]
Directly linking to #16 which shows how its possible, this is what the stetho sample app does.

**Comment by gitanshu** [comment]
Recently came across a production app which forgot to disable stetho. Can we update README to convey that devs should use it the way sample app does instead of just directly copying the string `compile 'com.facebook.stetho:stetho:1.5.0'` as recommended by current README?

**Comment by jasta** [comment]
@gitanshu note that technically having Stetho active in a release build is not necessarily an invalid configuration.  In fact, it's also not even a security flaw given that virtually all Android phones have severe security issues associated with having physical access to the device that would allow you to access app data files in much the same manner Stetho can.  Likewise, sniffing HTTP traffic can be done with a simple device wide VPN proxy, and of course the view tree is provided by `adb shell dumpsys top`.  In other words: stetho isn't a security flaw, it's just shipping excess code not likely to get used in production so folks should want to exclude it to save APK space.
