### ISSUE TITLE
if my DB file not in databases directory how to add this directory to let stetho find it

### ISSUE THREAD

**Issue by z2wenfa** [facebook/stetho#445]
Sometimes,i create db file in sdcard,if i can add that path,it will be very convenient for me.

**Comment by longinoa** [comment]
You can do this when you initialize Stetho.
If you look at https://github.com/facebook/stetho/blob/master/stetho-sample/src/debug/java/com/facebook/stetho/sample/SampleDebugApplication.java#L67 see how it is adding another provider?

You can create your own using this constructor https://github.com/facebook/stetho/blob/master/stetho/src/main/java/com/facebook/stetho/inspector/database/SqliteDatabaseDriver.java#L64 then just give it a `DatabaseFilesProvider` that lists your databases.
