### ISSUE TITLE
Introduce ability to disable CLog message redirection to LogCat

### ISSUE THREAD

**Issue by q1p** [facebook/stetho#450]
I'm using Stetho console logging for staging builds of app to help QA see what happens inside.
I have separate logging layer where any utility can be used depending on build configuration and I want to leave both regular `LogCat` and Stetho's `CLog`. The problems is `CLog` also writes to `LogCat` with own tag and always using `debug` level which makes messages harder to read and also duplicates them.
Looking for ability to configure `CLog` or disable inner `LogRedirector`.

**Comment by longinoa** [comment]
Are you currently calling `LogRedirector#setLogger`? That is how you control the `LogDirector`.

Its been a while since I have looked in this particular area but it appears you can do what you are looking for using that call.

**Comment by q1p** [comment]
Thank you for the advice.

I've tried to set dummy implementation of `Logger` to `LogRedirector` and skip all messages. In this case messages from `Stetho` will also be skipped because `LogUtil` uses `LogRedirector`.

The only way I found is to filter by hardcoded `CLog` tag. This solution does not look so elegant so I'm looking for a more friendly way to skip redirection.

**Comment by longinoa** [comment]
I think filtering the hardcoded `CLog` tag is the right way given what you are looking to do and the code as its written.

We would accept a PR to clean this code up a bit, but I dont think we have cycles to do this right now.
