### ISSUE TITLE
Don't show custom datbases which not under default database dir

### ISSUE THREAD

**Issue by wwluo14** [facebook/stetho#451]
First, i created a database under sqlite default database dir(/data/data/<package_name>/database), and i can find this database on Web SQL.
Second, i created a database under <getCacheDir()>/database, and i can't find my custom database on Web SQL. Stetho can only show database under default dir?

**Comment by longinoa** [comment]
This was added in v1.3.0

When you create your `SqliteDatabaseDriver` pass in a custom `DatabaseFilesProvider`. You can use `DefaultDatabaseFilesProvider` as a kind of template to use to create your own.

**Comment by wwluo14** [comment]
tks
