### ISSUE TITLE
Edit SQLIte database from within "table" view

### ISSUE THREAD

**Issue by mitchhentges** [facebook/stetho#453]
In "Resources > Web SQL", rather than having to `UPDATE Table SET bork='borkbork' WHERE property='requirement'` whenever I want to change a "cell", it would be neat-o if Stetho let me just edit a cell manually by double-clicking and editing its value.

**Comment by longinoa** [comment]
This would be awesome, however this isn't stetho's user interface, its the developer tools interface and we cant really control that part.

**Comment by mitchhentges** [comment]
@longinoa  Doesn't the `Chrome Developer Tools` interface support it?
![out](https://cloud.githubusercontent.com/assets/7784737/19882528/8d105906-9fcb-11e6-8b8d-c1a7bdf6b73f.gif)

**Comment by longinoa** [comment]
@mitchhentges there is a difference between "Local Storage" and "Web SQL". Local Storage is a key/value store that in stetho we expose as the shared preferences store (see `DOMStorage.java`).

We use the Database part of the protocol for the `Web SQL` section: https://github.com/facebook/stetho/blob/master/build-tools/protocol.json this just supports `executeSql` as the command.

**Comment by mitchhentges** [comment]
Ah, that makes sense. Thanks!
