### ISSUE TITLE
Timber: Add tag

### ISSUE THREAD

**Issue by PaulWoitaschek** [facebook/stetho#460]
The core feature of timber for me is that it generates an appropriate tag. 

However this is not used at all by stetho so I have no idea where the logs come from (which makes the logging quite useless). Is it possible that stetho displays the tag like timbers debug tree does?

**Comment by SiebeSysmans** [comment]
A pull request (#490) is open that adds this functionality.

**Comment by maks** [comment]
@SiebeSysmans are you still planning to amend the PR to get it merged?

**Comment by jasta** [comment]
The PR was rejected but should be commandeered if there's sufficient interest in bringing this back.  Closing for now.
