### ISSUE TITLE
StethoURLConnectionManager usage

### ISSUE THREAD

**Issue by arvi** [facebook/stetho#461]
Hello, I'm trying to make network interceptor work for urlconnection and according to docu:

> If you are using HttpURLConnection, you can use StethoURLConnectionManager

Do you have any example doing so? I can't find any articles about it. 

Here is my VolleySingleton snippet where I'd like to add it:

```java
    private RequestQueue getRequestQueue() {
        HurlStack hurlStack = new HurlStack() {
            @Override
            protected HttpURLConnection createConnection(URL url) throws IOException {
                HttpsURLConnection httpsURLConnection = (HttpsURLConnection) super.createConnection(url);
                try {
                    httpsURLConnection.setSSLSocketFactory(getSSLSocketFactory());
                    httpsURLConnection.setHostnameVerifier(getHostnameVerifier());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                return httpsURLConnection;
            }
        };

        if(mRequestQueue == null) {
            mRequestQueue = Volley.newRequestQueue(mCtx.getApplicationContext(), hurlStack);
        }
        return mRequestQueue;
    }
```

My build.gradle
```
    compile 'com.facebook.stetho:stetho:1.4.1'
    compile 'com.facebook.stetho:stetho-urlconnection:1.4.1'
```

**Comment by longinoa** [comment]
You can look at the [sample app](https://github.com/facebook/stetho/blob/master/stetho-sample/src/main/java/com/facebook/stetho/sample/Networker.java) to see how we have integrated with `StethoURLConnectionManager`. 
Using volley with `HttpURLConnection` will not work as you need to discretely handle the state machine in `StethoURLConnectionManager`. 

Volley should work with OkHttp which has documentation in various places See (https://github.com/facebook/stetho/pull/51#issuecomment-109102709)

**Comment by arvi** [comment]
@longinoa thanks for the tip, i'll check it out.
