### ISSUE TITLE
Chrome only shows a white screen

### ISSUE THREAD

**Issue by carlospaulino** [facebook/stetho#462]
Trying to inspect using Chrome only shows a white screen.
This is Chrome 54.0.2840.98 (64-bit) on OSX 10.11.6

![screen shot 2016-11-30 at 8 09 30 pm](https://cloud.githubusercontent.com/assets/625538/20776779/1a1222ec-b739-11e6-8f43-fcd1823daf05.png)

Looking at logcat I can see that stetho was initialized and that is supposed to be listening.

```
com.facebook.stetho.sample I/SampleDebugApplication: Stetho initialized in 5 ms
com.facebook.stetho.sample I/stetho: Listening on @stetho_com.facebook.stetho.sample_devtools_remote
```

Any tips on debugging this issue?

**Comment by longinoa** [comment]
Can you verify this in the sample app? This could be one of many things.

**Comment by carlospaulino** [comment]
@longinoa This is happening with the sample app as well.

**Comment by longinoa** [comment]
Okay that kind of points to a chrome and or adb issue. 

Can you use the chrome browser on your phone and try to attach to that from your desktop? Im just trying to understand where the breakdown is

**Comment by carlospaulino** [comment]
@longinoa You were right, inspecting chrome on the phone also shows the same white screen.

**Comment by rickbrew** [comment]
Are you using Android Studio and Instant Run? I've been running into the same thing and I think I have a fix.

**Comment by longinoa** [comment]
@rickbrew since inspecting a chrome instance on the device is showing the same symptoms it is likely a different problem, right?

**Comment by rickbrew** [comment]
Yeah if stetho isn't part of the stack then it must be something else

**Comment by xiabi** [comment]
I have issues same as you on Mac. Have you solved this question? Anyone who know how please help me.Thank u

**Comment by longinoa** [comment]
Are you using Android studio and instant run?

Get Outlook for Android

________________________________

**Comment by xiabi** [comment]
Thanks for reply.

I get into this issue with instant run and full build.

**Comment by AdamSHurwitz** [comment]
I have been having the same issue as well on my Mac. I tested Stetho out ~1 year ago with no issues and in Septemeber when I re-implemented at work Chrome was showing a white screen. 

I will try it again tomorrow and provide the Android API Level as well as my Mac OS if it is still occuring.

**Comment by xiabi** [comment]
compileSdkVersion 23
buildToolsVersion 25.0.1
chromeVersion 50.0.2661.102 (64-bit)
MacVersion OSX 10.11.5 (15F34)

**Comment by rickbrew** [comment]
Okay this might have fixed it: #465

**Comment by xiabi** [comment]
thanks for your work.

but it seem that this problem still exists.

![image](https://cloud.githubusercontent.com/assets/12221657/21124599/dd8f5d12-c11a-11e6-9e94-bed3ab4ad634.png)

**Comment by longinoa** [comment]
@xiabi try connecting to a chrome instance on your phone. If you get the same white box then it is something between chrome and your phone

**Comment by carlospaulino** [comment]
@longinoa Fully wiping Chrome and reinstalling fixed the issue for me. 

Thanks a lot for the support.

**Comment by brunovlucena** [comment]
Just try to restart the adb-server. I had the same problem as i left the pidcat running and tried to access the 'inspect' link

**Comment by xiabi** [comment]
hello. i try stetho these time. and it is still not working with me.
![image](https://cloud.githubusercontent.com/assets/12221657/23844453/424d5212-07fd-11e7-9e18-8f253bc5ed5e.png)

and i find something else. when i open the console view in chrome. 
![image](https://cloud.githubusercontent.com/assets/12221657/23844501/77770a1e-07fd-11e7-9bb5-3c3855b1ecb4.png)
maybe it will figure out the problem if u help me.

thanks alot

**Comment by awcoding** [comment]
FYI - I tried v1.4.2 and while other chrome inspect functionality (eg. prefs) worked, sqlite access didn't. (No .db file appeared in the dropdown) Downgrading to 1.3.1 fixed that issue for me. So I think there has been a regression there.

**Comment by pcqpcq** [comment]
https://github.com/GoogleChrome/ADBPlugin/issues/14

**Comment by sudhan-ionic** [comment]
I found solution
Pls update chrome, it will fix an error 
`chrome://settings/help`

**Comment by gbrt46** [comment]
I also had the same problem. Try following steps to fix that
1. Go to Phone settings
2.Search for the chrome app
3.Disable the chrome app(This will uninstall the updated version of chrome).
4.Enable it again.

Note: Later you can update the chrome via play store too.

**Comment by rasoulmiri** [comment]
Check this ways:
1. update chrome in mobile and in windows or mac
2. use VPN for connect to server google (China, Iran,...)

**Comment by rasoulmiri** [comment]
Check this ways:
1. update chrome in mobile and in windows or mac
2. use VPN for connect to server google (China, Iran,...)

**Comment by haiyang1994** [comment]
thanks. i solve it by using vpn.
thanks, all guys!

**Comment by shuklashubhansh** [comment]
This might be also the case that Android webview is not updated.

I tried everything but the issue got resolved when I updated Android system webview.

To do this go to playstore>android system webview and hit update!

**Comment by plakerco** [comment]
In my case it helped to deinstall the Android system webview

**Comment by ankerpeet** [comment]
I was having this same issue, then I downloaded Chromium and it works now!
