### ISSUE TITLE
multi database with the same name, but in different directories.

### ISSUE THREAD

**Issue by jiangecho** [facebook/stetho#467]
With custom ```DatabaseFilesProvider```, we can provider multi database files with the same name, but lie in different directories.
Due the ```findDatabaseFile``` logic in ```SqliteDatabaseDriver```, we can only interact with the first database.

**Comment by longinoa** [comment]
@jiangecho Can you do something in your custom provider where you change the name to be `directory-actualName` You would then know what you have to perform the stripping when calling into `SqliteDatabaseDriver`

**Comment by jiangecho** [comment]
@longinoa Thank you for your reply. Yeah, it's a solution for my case.
