### ISSUE TITLE
url with port seems not work

### ISSUE THREAD

**Issue by b95505017** [facebook/stetho#47]
I use StethoInterceptor in OkHttp 2.2.0
ex. http://www.google.com/blabla/blabla, this link could show in CDT.
But if link change to http://www.google.com:8080/blabla/blabla, this links couldn't show in CDT.
Should I encode this link into some format?

**Comment by jasta** [comment]
Hmm that's weird that it wouldn't work with non standard ports.  The layer at which Stetho intercepts isn't affected by the actual network layers at all.  Can you repro this in a sample/demo app?

**Comment by b95505017** [comment]
I found that it is causing by other issue, I filled another one #57 .
Sorry.
