### ISSUE TITLE
stetho & stetho-okhttp conflict with findbugs

### ISSUE THREAD

**Issue by mahdihijazi** [facebook/stetho#471]
In our project we include the 
compile 'com.google.code.findbugs:annotations:3.0.0'

then we started to see this error:
`Caused by: java.io.IOException: Can't read [/var/jenkins/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/2.0.1/516c03b2/jsr305-2.0.1.jar] (Duplicate zip entry [jsr305-2.0.1.jar:javax/annotation/CheckForNull.class])`

stetho included findbugs module in 
https://github.com/facebook/stetho/blob/master/stetho/build.gradle

instead of the compile 'com.google.code.findbugs:annotations:3.0.0' which causes a conflict since both the findbugs one and the annotations module define the same check.

do you really need to include the findbugs module for stetho?

same issue with stetho-okhttp

**Comment by jasta** [comment]
Hmm, this bug actually seems like it's with `com.google.code.findbugs:annotations` actually.  `annotations` includes all of `net.jcip.annotations`, `edu.umd.cs.findbugs.annotations`, _and_ `javax.annotation` whereas `com.google.code.findbugs:jsr305` contains only `javax.annotation`.  If `com.google.code.findbugs:annotations` was to actually depend on `jsr305` internally then you wouldn't have an issue here.

Looking closer, it would seem that Google even noticed this issue already and corrected it by adding a new maven artifactId that has the correct dependencies: `com.google.code.findbugs:findbugs-annotations:3.0.1` should work perfectly for you.
