### ISSUE TITLE
View Hierarchy

### ISSUE THREAD

**Issue by Aleksandern** [facebook/stetho#477]
Hello.

Can someone tell me why can't I see "listview", "textview", "image view" etc elements in "Elements" tab?
There are only something like this: "com.facebook.react.views.view.reactviewgroup" or "com.facebook.react.views.view.reactextview"

![ss 2016-12-28 at 12 55 06](https://cloud.githubusercontent.com/assets/5274465/21514945/8f5316f4-ccfd-11e6-98dc-7476371e6c40.png)

It doesn't look like this:
![inspector-elements](https://cloud.githubusercontent.com/assets/5274465/21514963/bcf98b24-ccfd-11e6-8732-9ed43b32b546.png)

API 21
stetho 1.4.2

Thanks

**Comment by longinoa** [comment]
Im not too familiar with our react code base but im guessing that those are the react equivalent to listview/textview/etc?

**Comment by longinoa** [comment]
for example, what happens if you use the stetho sample app

**Comment by Aleksandern** [comment]
Yes those are react equivalent to listview etc... but it's not comfortable to work with equivalents :)
I use [nuclide](https://nuclide.io/docs/platforms/react-native/#debugging__element-inspector) to inspect elements.
