### ISSUE TITLE
Stetho Only shows 250 values

### ISSUE THREAD

**Issue by parth103** [facebook/stetho#478]
Stetho only shows 250 values , how to increase that values , because i am inserting data every seconds in my database.

**Comment by Isanderthul** [comment]
you can not increase it. 
you could copy the db to your hard drive and inspect it
```
adb shell "su -c cp data/data/com.example.myapp/databases/database storage/sdcard0/Download"
adb pull /sdcard/Download/database
```

**Comment by longinoa** [comment]
you can use sql to select the values you care about. 

There isnt a way to get developer tools to page the data so returning an arbitrarily large number of records would be not only a bad user experience, but also take forever to transmit it over the protocol.
