### ISSUE TITLE
No inspect button are appear

### ISSUE THREAD

**Issue by pedrohenriquerls** [facebook/stetho#480]
I followed the tutorial [here](https://facebook.github.io/react-native/docs/debugging.html), but I cant inspect.
The device is a emulator and am using the Ubuntu 16.04.
I have the server running and everything looks ok, but the option to inspect never appears.

![screenshot from 2017-01-08 01-55-03](https://cloud.githubusercontent.com/assets/952303/21747161/9909d7d2-d545-11e6-98f6-b125e49da6a8.png)

**Comment by aandis** [comment]
hitting this. I have a physical device and trying on ubuntu 14.04

**Comment by aandis** [comment]
Fixed by adding my created `Application` class to manifest.

**Comment by jasta** [comment]
Can you check that `stetho-sample` works properly (download the sources and run `./gradlew installDebug`, find and run the sample, then look at `chrome://inspect`)?

**Comment by jasta** [comment]
Closing due to #551
