### ISSUE TITLE
Error: Could not bind to socket

### ISSUE THREAD

**Issue by eleventigers** [facebook/stetho#49]
Upon starting an app, stetho fails to setup a server here:

https://github.com/facebook/stetho/blob/69a9ec51b93dc7eed122900ca5bbb823e6aa4ab9/stetho/src/main/java/com/facebook/stetho/server/LocalSocketHttpServer.java#L287

Not sure what I am doing wrong and whether there is anything particular needed to be configured on my test device (Nexus 5/6)?

**Comment by eleventigers** [comment]
It seems that you can not have a debugger attached at the same time as having devtools open hence "Address already in use" error.

**Comment by jasta** [comment]
I've noticed this bug myself but I think it's actually harmless.  The binding error appears to be the result of a logic bug that tries to bind twice, with the second time of course failing.  The first bind works and the system should remain functional.

I'm going to see about fixing this properly today.

**Comment by jasta** [comment]
Facepalm: `while (retries > 0) { ... bind(); }`

**Comment by golenazfazli** [comment]
Sorry! I had mistake!!!
