### ISSUE TITLE
Enable stetho to intercept local traffic (like for wiremock)

### ISSUE THREAD

**Issue by krzysztof-paliga-perform** [facebook/stetho#496]
It seems to me like currently Stetho isn't able to intercept local traffic (like to 127.0.0.1 running wiremock).

**Comment by jasta** [comment]
I saw that you closed the issue but I wanted to reply anyway for documentation purposes.

Stetho doesn't actually intercept any traffic at the socket level, it merely reports on the traffic it's told about.  For this to work we hook common libraries like okhttp to forward request/response information to Stetho which then sends it along to Chrome.

To get your traffic to show up take a look at the stetho-sample to show how you can inform Stetho of traffic using HttpURLConnection or just drop in StethoInterceptor if you use okhttp.  For other third party libraries you're likely going to need to either Google for a Stetho bridge for the library or roll your own.  StethoInterceptor.java is probably a good place to start to figure out how that would work (it should be pretty easy!)
