### ISSUE TITLE
dumpapp not accepting any stdin data

### ISSUE THREAD

**Issue by mariotaku** [facebook/stetho#509]
## Expected:

Execute `./dumpapp -p packageName pluginName < someLocalFile.txt` on computer, and `DumperPlugin` have contents in someLocalFile.txt to read.

## Actual:

stdin not receiving any data, attempt to `read()` throws EOFExcepion, on computer side I got
````
Traceback (most recent call last):
  File "./dumpapp", line 84, in <module>
    main()
  File "./dumpapp", line 47, in main
    read_frames(sock)
  File "./dumpapp", line 73, in read_frames
    sock.send(b'-' + struct.pack('!L', -1))
struct.error: argument out of range
````

**Comment by jasta** [comment]
Hmm, I wonder if we have a protocol mismatch here.  We changed the protocol
about a year ago and updated the client scripts to be backwards compatible
with the exception of stdin so it may just be that your client scripts are
out of date.  That said I had thought we made it warn to this effect but I
could be mistaken.

**Comment by jasta** [comment]
I just verified that stdin is working via the sample app:

  echo foo | ./scripts/dumpapp -p com.facebook.stetho.sample hello -

Can you try this as well?  To install the sample just invoke `./gradlew installDebug`.  Then run the main activity and then finally the above command.

**Comment by jasta** [comment]
Oh and I see the hello world plugin would not see this problem since it reads until the newline occurs and stops.  All you have to do to trigger is:

  echo -n foo | ./scripts/dumpapp -p com.facebook.stetho.sample hello -

And you trigger.  OK, I'll throw up a PR to fix shortly.

**Comment by mariotaku** [comment]
Thanks!
Josh Guilfoyle <notifications@github.com>于2017年3月10日 周五22:49写道：

**Comment by jasta** [comment]
The good news is that the fix is entirely in dumpapp so you can just grab
the patch from the PR and have a fix locally.

**Comment by mariotaku** [comment]
@jasta That patch works for me 👍
