### ISSUE TITLE
Error Syncing Gradle File for stetho-sample

### ISSUE THREAD

**Issue by BIGxRED** [facebook/stetho#517]
I've downloaded the stetho-sample project and when I first open it within Android Studio, I receive the following error within the build.gradle file:

`Plugin with id 'com.android.application' not found`

I don't have very much experience with Gradle other than listing out my dependencies. Anyone have any idea as to what the source of the issue is? I am using Android Studio 2.3.

**Comment by jasta** [comment]
Try `./gradlew installDebug` on the command-line.  If that works for you, odds are you just need to make sure Android Studio is configured (in the settings) to use the local gradle wrapper not your system gradle.

**Comment by BIGxRED** [comment]
I ran the command that you mentioned and this is the output that I received:

`FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Mike\AndroidStudioProjects\stetho-sample\build.gradle' line: 6

* What went wrong:
A problem occurred evaluating root project 'stetho-sample'.
> Plugin with id 'com.android.application' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.945 secs
`

Any additional guidance on this? I can also rerun the command with the `--stacktrace` option if you'd like.

**Comment by jasta** [comment]
Hmm.  And you can build other Android apps just fine?  That's quite odd.  I guess try what it says and add --info and/or --debug to see if it reveals more info.  My first guess was that you didn't have the Android SDK installed or something but the output certainly isn't conclusive.
