### ISSUE TITLE
After introducing the project compiler error

### ISSUE THREAD

**Issue by Sailiy** [facebook/stetho#518]
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Ljavax/annotation/CheckForNull;

**Comment by jasta** [comment]
See #471.  If you're using findbugs annotations this is expected due to an issue with their packaging.  It can be fixed by using the target mentioned in the task though admittedly Stetho can also fix this by treating jsr305 as optional.
