### ISSUE TITLE
Support for response buffering

### ISSUE THREAD

**Issue by bangarharshit** [facebook/stetho#520]
One of the biggest issue with Stetho is that the network response is not buffered and it can result in few issues:
1. Loose network calls before the bridge is connected.
2. Doesn't work across the session.

It will be great if Stetho can provide any kind of buffering (it can be optional/configurable). The architecture can be simple - interceptor is inserting the content in a persistent queue, and the data is read from the same.

https://github.com/facebook/stetho/blob/master/stetho-okhttp/src/main/java/com/facebook/stetho/okhttp/StethoInterceptor.java

**Comment by jasta** [comment]
I've also been thinking about this a lot lately but I don't have any clear design proposals yet.  One idea would be to simply buffer network events on disk and then when a new client connects replay them all back.  But there are gotchas with visualization here (notably there's no negative time so it would all appear as having happened "now").  I'm very interested in a PR here if you could throw something together that works consistently.
