### ISSUE TITLE
Stetho network interceptor doesn't show requests until there's response from server

### ISSUE THREAD

**Issue by Dragas** [facebook/stetho#536]
Right now, stetho seems to ignore requests before it is actually made. According to `okhttp3.internal.cache.CacheInterceptor:72` request might fail before it is dispatched to the world wide web and not get captured by Stetho network interceptor. It also seems that Network interceptors are added way after all other (be it cache, bridge and other user defined non-network) interceptors (`okhttp3.RealCall:179`).

A solution here would be to add another, non-network, interceptor that developers could add while building their okhttp3 clients.

**Comment by jasta** [comment]
Not sure what exactly you mean but I am intrigued.  Stetho endeavors to accurately capture the actual network traffic that occurs in an app but could be extended to support Chrome's concept of caching with a bit of effort.  That said, it would be fairly difficult to expose this in a general way outside of just okhttp integration.  Closing for now to clean up our issue queue (LONG OVERDUE, MY GOSH!!!), but feel free to re-open for further discussion if you are interested in driving this a bit.
