### ISSUE TITLE
Is it possible to customize the query results?

### ISSUE THREAD

**Issue by Arvalon** [facebook/stetho#537]
Is it possible to customize the query results? In the shell, sqlite has the ability to control the appearance by using commands ".mode" and others.
But then when you try to apply them displayed a syntax error
![stetho_sql_error](https://cloud.githubusercontent.com/assets/19150332/26451308/3e5d1700-4164-11e7-8b02-42acdad25e81.PNG)

**Comment by jasta** [comment]
Basically no.  Those features are all internal to the sqlite3 command-line tool sadly.
