### ISSUE TITLE
Blank white screen when clicking on inspect to launch the Stetho

### ISSUE THREAD

**Issue by eddywm** [facebook/stetho#538]
I have tried to use the Stetho tool to debug my sqlite db after following the instructions on the project page, but the problem with it is I am getting a white blank screen in Chrome when launching the application.

![stetho problem on ubuntu linux chrome](https://user-images.githubusercontent.com/25495376/27555293-fbd893f4-5ab9-11e7-9c34-a0829783e202.png)

**Comment by jasta** [comment]
See #462.  Basically, update chrome.

**Comment by Stupilan1** [comment]
This isnt a fix
