### ISSUE TITLE
cannot check the realm database，when i create realm database with my own name

### ISSUE THREAD

**Issue by davidgerka** [facebook/stetho#542]
I create the realm dataBase like this ：
Realm.setDefaultConfiguration(
new RealmConfiguration.Builder().name("UserDAO_" + userID + DATABASE_POSTFIX_NAME)
                .deleteRealmIfMigrationNeeded().build());
Then,i want to use stetho and chrome to check my database, i found that ,i can only see  the database name, i cannot check the content.How can i do that?Thanks

**Comment by jasta** [comment]
See: https://github.com/uPhyca/stetho-realm
