### ISSUE TITLE
EvaluatorException for sql query

### ISSUE THREAD

**Issue by ubaierbhat** [facebook/stetho#546]
Version: 1.5.0

I get an EvaluatorException when running an SQL query from the console; 
eg; `SELECT _id FROM User;`

The cause of error seems to be 
> "missing ; before statement"

but I have a `;` in the query

> Uncaught EvaluatorException
Object.shadow$_klass_: ClassObject.shadow$_monitor_: -1961575788RhinoException.columnNumber: 19RhinoException.interpreterLineData: nullRhinoException.interpreterStackInfo: nullRhinoException.lineNumber: 1RhinoException.lineSource: "SELECT _id FROM User;"RhinoException.sourceName: "chrome"Throwable.cause: EvaluatorExceptionThrowable.detailMessage: "missing ; before statement"Throwable.stackState: arrayThrowable.stackTrace: arrayThrowable.suppressedExceptions: List

**Comment by hoanv810** [comment]
I'm facing the same problem. 
Have included semicolons before and after my statement but nothing changed.

**Comment by potyl** [comment]
Can you try a simple javascript expression `2 + 3` and see if it evaluates?

Also try disabling stetho-js-rhino.

**Comment by ubaierbhat** [comment]
`2 + 3` does evaluate.

**Comment by emitchel** [comment]
Also seeing this issue, didn't before.

**Comment by raghulvelusamy** [comment]
Also seeing this.

**Comment by jasta** [comment]
The console doesn't support arbitrary SQL statements, but it does support JavaScript statements via stetho-js-rhino.  To use SQL statements, go to the Resources tab and select WebSQL.

**Comment by VihaanVerma89** [comment]
I think this is not working in version 1.5.0 and it throws "missing ; before statement". I just added 
```
    compile 'com.facebook.stetho:stetho:1.5.0'
    compile 'com.facebook.stetho:stetho-js-rhino:1.5.0'
```

and
`        Stetho.initializeWithDefaults(this);
`
in my Application class. 

Ran the app -> chrome://inspect -> Clicked on inspect app -> Resources tab -> "select * from $table"
```
_____/\\\\\\\\\\\_______________________________________________/\\\_______________________
 ___/\\\/////////\\\____________________________________________\/\\\_______________________
  __\//\\\______\///______/\\\_________________________/\\\______\/\\\_______________________
   ___\////\\\__________/\\\\\\\\\\\_____/\\\\\\\\___/\\\\\\\\\\\_\/\\\_____________/\\\\\____
    ______\////\\\______\////\\\////____/\\\/////\\\_\////\\\////__\/\\\\\\\\\\____/\\\///\\\__
     _________\////\\\______\/\\\_______/\\\\\\\\\\\_____\/\\\______\/\\\/////\\\__/\\\__\//\\\_
      __/\\\______\//\\\_____\/\\\_/\\__\//\\///////______\/\\\_/\\__\/\\\___\/\\\_\//\\\__/\\\__
       _\///\\\\\\\\\\\/______\//\\\\\____\//\\\\\\\\\\____\//\\\\\___\/\\\___\/\\\__\///\\\\\/___
        ___\///////////_________\/////______\//////////______\/////____\///____\///_____\/////_____
         Welcome to Stetho
          Attached to last.seen.hider.for.whatsapp

select * from Chats;
Uncaught EvaluatorExceptionObject.shadow$_klass_: ClassObject.shadow$_monitor_: -1943706498RhinoException.columnNumber: 20RhinoException.interpreterLineData: nullRhinoException.interpreterStackInfo: nullRhinoException.lineNumber: 1RhinoException.lineSource: "select * from Chats;"RhinoException.sourceName: "chrome"Throwable.backtrace: arrayThrowable.cause: EvaluatorExceptionThrowable.detailMessage: "missing ; before statement"Throwable.stackTrace: arrayThrowable.suppressedExceptions: List

```

**Comment by VihaanVerma89** [comment]
Ok, If you were stuck just like me. You might be entering the query in the javascript console. The queries work only the box below the Resources Tab and not the Console . Everyone does silly mistakes ;)

**Comment by 4sskick** [comment]
@VihaanVerma89 I've been follow your instruction, but nothing displayed on Resource Tab

**Comment by eliasbagley** [comment]
I'm having this problem too.

**Comment by abiemann** [comment]
I need a picture of what Vihaan described.
I'm not having any luck executing sqlite commands... picture of what I'm seeing: 

https://drive.google.com/open?id=161OjhQTUhwL2_CwTUALKb7Pekd5Nha7s

**Comment by pedrofsn** [comment]
I watched the video before and was exactly what I'm doing but it doesn't work.
When I hit enter, the "query editor" just break the line and not "evaluate expression".

I tried enter, shift + enter and ctrl + enter.  =/

**Comment by nareshpraana** [comment]
You have to click on the db and use the console at the beginning.
