### ISSUE TITLE
Does Stetho works with RoomDataBase ?

### ISSUE THREAD

**Issue by mwshubham** [facebook/stetho#548]
I was migrating my project from SQLite to RoomDatabase but I couldn't inspect the database using Stetho. Does it support RoomDatabase ? or it is in WIP.

**Comment by itscorey** [comment]
Yes, it does.

Stetho is working fine with Room.

![image](https://user-images.githubusercontent.com/20311112/29480300-b6035e00-844d-11e7-9342-a2519614d93d.png)

How are u trying?

**Comment by mwshubham** [comment]
Yeah, It does. There might be some problem at the time of creating this issue. Thanks for your reply.

**Comment by pacifire** [comment]
@mwshubham  @itscorey : Here is the [code](https://github.com/googlecodelabs/android-persistence), in which i have integrated the Stetho.

But am not able to see the Table structure/ Data in the Chrome: Check screenshot below:

![screen shot 2018-03-21 at 6 24 55 pm](https://user-images.githubusercontent.com/5895976/37710924-341184da-2d35-11e8-9c4b-f5162e191def.png)

Please help, what i am doing wrong.

**Comment by Menris** [comment]
@pacifire My problem was that I couidn't see my database because it was an empty database with no data. I tried to populate one table and after that I could see DB in Stetho.

**Comment by RunningShadow-007** [comment]
I suffered the same problem

**Comment by Menris** [comment]
@RunningShadow-007 My problem was I couldn't see my database with no data. Finallt Room showed it after any Query operation is used on your database.

**Comment by smitsgit** [comment]
@pacifire i think i understand why you were not seeing it in Stetho.
The persistent codelab uses in memory database
` public static AppDatabase getInMemoryDatabase(Context context) {
        if (INSTANCE == null) {
            INSTANCE =
                    Room.inMemoryDatabaseBuilder(context.getApplicationContext(), AppDatabase.class)
                    // To simplify the codelab, allow queries on the main thread.
                    // Don't do this on a real app! See PersistenceBasicSample for an example.
                    .allowMainThreadQueries()
                    .build();
        }
        return INSTANCE;
    }`
Change this to 
Room.databaseBuilder(context.getApplicationContext(), AppDatabase.class, 'test.db')

And you will see the DB in the Stetho.
![image](https://user-images.githubusercontent.com/11153931/55224841-5688de00-5237-11e9-8c2c-a800496654ce.png)
