### ISSUE TITLE
Please introduce Horizontal Scroll

### ISSUE THREAD

**Issue by scorchgid** [facebook/stetho#561]
I use Stetho to view the [realm](https://realm.io/) I am making on my phone, the trouble is I have a lot of cells when I create my realm this is what I get 
![image](https://user-images.githubusercontent.com/6419740/29741479-8d2f2eaa-8a65-11e7-9c29-e65a001fef26.png)

I am not able to change my schema particularly for something I use to debug. But as this is part of my project I need to be able to prove the data exists. If this is the wrong place to make this request let me know.

Thank you very much for you time :)

**Comment by cezar-carneiro** [comment]
I think stetho can't do that, unfortunately. Only chrome could change it's components.
see this: #153

**Comment by jasta** [comment]
@cezar-carneiro sadly, yes.  We can't implement this without changes in Chrome itself.  However, Stetho is extensible enough to potentially add our own UI on top of Chrome or even extend Chrome's.  This is something long term we're interested in but just haven't been able to quite get it off the ground yet.
