### ISSUE TITLE
stetho-urlconnection depends on stetho-okhttp3

### ISSUE THREAD

**Issue by MohamadAtieh** [facebook/stetho#565]
Hey,

I am trying to implement my own version of an `HttpStack` with Volley. There is no http3 support in my project yet and I noticed that when I try initializing `StethoURLConnectionManager` without compiling `com.facebook.stetho:stetho-okhttp3:1.5.0`, I get that `nextRequestId()` does not exist in the sources

However, when I add `stetho-http3` library, it works fine. 

I am wondering why in the README you only mentioned using either one of them and not both.

**Comment by jasta** [comment]
I'm not sure what you're referring to here.  `StethoURLConnectionManager` does not intentionally depend on okhttp or the okhttp `StethoInterceptor` and I can't see any evidence that there's an accidental dependency in play.  The stetho-sample app for example doesn't include okhttp at all and works perfectly with `StethoURLConnectionManager`.
