### ISSUE TITLE
Stetho does not show Database

### ISSUE THREAD

**Issue by zcqzcq** [facebook/stetho#567]
Stetho does not show Database and ...
![image](https://user-images.githubusercontent.com/13348242/31043158-05a8b064-a5ea-11e7-8d45-e2a02d9970e0.png)

**Comment by NitramTasu** [comment]
@zcqzcq Maybe this can help you:
https://github.com/facebook/stetho/issues/462
https://github.com/googlearchive/ADBPlugin/issues/14

**Comment by zcqzcq** [comment]
thanks, I find an other
