### ISSUE TITLE
some response not showing in network tab

### ISSUE THREAD

**Issue by b95505017** [facebook/stetho#57]
Some response header doesn't have any "Content-Type", is that the root cause?

**Comment by b95505017** [comment]
I changed StethoInterceptor code these line, then those responses appear into network tab successfully.

````java
try {
    response = chain.proceed(request);
    if (response.body().contentType() == null) {
        response = response.newBuilder().header("Content-Type", "text/html").build();
    }
} catch (IOException e) {
    if (mEventReporter.isEnabled()) {
        mEventReporter.httpExchangeFailed(requestId, e.toString());
    }
    throw e;
}
````

**Comment by jasta** [comment]
Thanks that's really helpful.  I'll fix this at a lower level so the fix
works for stetho-urlconnection too.

**Comment by b95505017** [comment]
Thanks, looking forward the next release!
Great library!

**Comment by longinoa** [comment]
Is the right course of action to assume text/html though? spec seems to indicate it should be application/octet-stream http://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html

**Comment by jasta** [comment]
@longinoa It's not actually a Content-Type problem, it's DevTools' internal concept of `ResourceType`.  We can convert a lack of `Content-Type` header to `ResourceType.OTHER` and it should work fine.

**Comment by jasta** [comment]
`mimeType` doesn't need to be faked but I do like using `application/octet-stream` anyway.  Just in case the DevTools folks break stuff later :)

**Comment by b95505017** [comment]
Thanks! May I ask when could we get this on Maven?

**Comment by jasta** [comment]
@b95505017 working on getting a release (1.0.1) out the door this week.

**Comment by b95505017** [comment]
:+1:
