### ISSUE TITLE
How to write to console any object?

### ISSUE THREAD

**Issue by ilyamuromets** [facebook/stetho#577]
How to write to console any object (Map, List, JSONObject, JSONArray, ...), not a String?
Is it possible to print object with expandable tree like as Chrome debugger?

**Comment by jasta** [comment]
I _think_ so, but I'm not sure exactly how.  See https://github.com/facebook/stetho/blob/master/build-tools/protocol.json, specifically "messageAdded" in the "Console" group.  There are a number of properties we don't expose that could, in theory, be used to do this though I'm unsure how at the moment.  A little help would be greatly appreciated :)

Closing pending additional research.
