### ISSUE TITLE
App crashes cause of NullPointerException

### ISSUE THREAD

**Issue by devjta** [facebook/stetho#580]
Hello!

I dont know why, but sometimes my app crashes, because Stetho has a NullPointerException in the OkHttpInspectorResponse - connectionId method. It will return the connection hashcode as ID, but it seems the connection is NULL which causes the exception and the crash of my app.

I cannot make a "workaround", as the OkHttpInspectorResponse is a privat class in the StethoInterceptor class.

And I cannot reproduce the bug all the time. Sometimes the app crashes while I am looking at tables or watching the network-traffic.

Here is the stacktrace of it:
`12-12 16:15:00.051 20886 24199 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference`
`12-12 16:15:00.051 20886 24199 E AndroidRuntime: 	at com.facebook.stetho.okhttp3.StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:226)`
`12-12 16:15:00.051 20886 24199 E AndroidRuntime: 	at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.responseHeadersReceived(NetworkEventReporterImpl.java:145)`
`12-12 16:15:00.051 20886 24199 E AndroidRuntime: 	at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:70)`
`12-12 16:15:00.051 20886 24199 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)`
`12-12 16:15:00.051 20886 24199 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)`

**Comment by jasta** [comment]
This occurs when you use addInterceptor instead of addNetworkInterceptor with OkHttp.  I'm going to apply a patch to Stetho to at least make this issue clearer since it gets reported a lot :)

**Comment by devjta** [comment]
You were right, I had used addNetworkInterceptor for all connections, but for the amazon-s3 connection I used addInterceptor...
Thanks for the help!
