### ISSUE TITLE
No main activity on 'Elements' tab

### ISSUE THREAD

**Issue by yshinkarev** [facebook/stetho#583]
I have <packageName.AppClassName></packageName.AppClassName> on main activity.
If I open new activity from main activity I get:
<packageName.AppClassName>
<SecondActivity>...</SecondActivity>
</packageName.AppClassName>
But why I have no same information on main activity (like SecondActivity)?

**Comment by jasta** [comment]
Activity tracking occurs automatically on Android API 14+, so you should see that as you transition around the app activities add and remove from the list automatically.  You will need to have chrome://inspect open however to see this behaviour, so if you close out and re-open again you may be missing the previously opened activities.
