### ISSUE TITLE
Problems of ChromeDevtoolsServer: Method not implemented 

### ISSUE THREAD

**Issue by iBotasky** [facebook/stetho#586]
@zpao Hello, I got a problem
Here is my gradle's setting
```
buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug{
            minifyEnabled false
            shrinkResources false
        }
    }
```
I'm closing the proguard  and there is not a relese version of app. But i can see any db or sp files in the Stetho.
![image](https://user-images.githubusercontent.com/13627665/35191344-e808f0b4-feb3-11e7-8a94-36109e977ef4.png)

And there is the log of the logs
```
01-21 00:53:43.239 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: Method not implemented: Not implemented: Debugger.setAsyncCallStackDepth
01-21 00:53:43.254 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: Method not implemented: Not implemented: Debugger.skipStackFrames
01-21 00:53:43.266 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: Method not implemented: Not implemented: Runtime.enable
01-21 00:53:43.321 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: Method not implemented: Not implemented: Worker.enable
01-21 00:53:43.332 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: Method not implemented: Not implemented: Timeline.enable
01-21 00:53:43.390 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.enable
01-21 00:53:43.402 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: Method not implemented: Not implemented: Page.getNavigationHistory
01-21 00:53:43.412 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: Method not implemented: Not implemented: Worker.setAutoconnectToWorkers
01-21 00:53:43.474 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
01-21 00:53:43.484 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: Method not implemented: Not implemented: Page.getNavigationHistory
01-21 00:53:55.625 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: Method not implemented: Not implemented: ApplicationCache.enable
01-21 00:53:55.635 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: Method not implemented: Not implemented: ApplicationCache.getFramesWithManifests
01-21 00:58:59.963 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
01-21 00:59:05.274 4262-4330/com.sirius.cybird D/ChromeDevtoolsServer: onClose: reason=1011 EOF while reading
01-21 00:59:05.274 4262-4330/com.sirius.cybird I/ResponseBodyFileManager: Cleaned up temporary network files.
```

**Comment by iBotasky** [comment]
The version of Stetho is `1.5.0`

**Comment by jasta** [comment]
Hmm, method not implemented doesn't look like the real culprit.  The onClose EOF while reading seems more interesting.  Is it possible your app is crashing or restarting itself after you are attached?

**Comment by iBotasky** [comment]
@jasta There is not crashing of my app, it still running on the emulator. Is this may be caurse by the emulator？

**Comment by jasta** [comment]
Hmm no that shouldn't be the issue.  We might be barking up the wrong tree here tho.  Do other parts of Stetho work properly, like the elements tree and/or the dumpapp command line tool?  If yes, I'm wondering if the issue is somehow that simply no databases were detected (if you do things in a non standard way you have to do a little bit of configuring to help stetho find the DB files).

**Comment by iBotasky** [comment]
@jasta Sorry about that. I use `ObjectBox` for my DB, and the `ObjectBox` team say that Stetho was not support for `ObjectBox`'s file(The DB is mdb file).
And I try to write a value with SP, and there I found the value in the Chrome devtool with Stetho.
![image](https://user-images.githubusercontent.com/13627665/35422767-4d541190-0285-11e8-9b10-44e11dd62782.png)
And the logcat still have the `No implement`'s log:
![image](https://user-images.githubusercontent.com/13627665/35422797-695130d0-0285-11e8-94a1-bf8e0e6b7f6c.png)
I think the `No implement` is  not a big problem. Because the other parts of Stetho is work properly.
Sorry for the troubles.
