### ISSUE TITLE
sqlite db not readable when number of columns are more

### ISSUE THREAD

**Issue by tushar091** [facebook/stetho#587]
Sqlite db becomes unreadable when number of columns are more
as when we browse columns horzontal scrolling is not available hence unable to view the columns properly
![screenshot from 2018-02-14 12-29-21](https://user-images.githubusercontent.com/12141330/36191384-e0f1eccc-1182-11e8-910d-afcf6fd095ab.png)

**Comment by longinoa** [comment]
This view is owned by chrome, and we cant do much about it.

One option here is to select the database rather than the table. This gives you the ability to execute sql commands so you can restrict what columns you are getting.
