### ISSUE TITLE
Support for SqlCipher

### ISSUE THREAD

**Issue by usergoodvery** [facebook/stetho#588]
Hi,
Is there a known mechanism for using stetho with db encrypted with SqlCipher. Or more directly, is there a way to provide the key to stetho?

**Comment by longinoa** [comment]
There is no current way to provide a key.

Seeing as how close SqlCipher is to SqlLiteDatabase you could look at creating a SqlLiteDatabaseProvider that bridges the two.

The other option is to create a DumperPlugin that would be able to do the queries for you.

**Comment by mathroule** [comment]
Hi.
I'm trying to use Stetho on an app using SqlCipher, I got this issue https://github.com/sqlcipher/android-database-sqlcipher/issues/328.
There is a way to disable database inspection and keep network monitoring in Stetho?

**Comment by mathroule** [comment]
If I'm trying to open the encrypted database in Chrome DevTools, the database become corrupted and the app crash on next startup. So one way to disable database inspection is to not use it.

**Comment by mathroule** [comment]
Stetho can decrypt SQLCipher database thanks to this plugin https://github.com/technoir42/stetho-sqlcipher.
