### ISSUE TITLE
cordova/phonegap plugin

### ISSUE THREAD

**Issue by sido420** [facebook/stetho#594]
Is it possible to use Stetho with Phonegap/Cordova apps? 

If not, are there any plans to create a plugin for Cordova/Phonegap?

**Comment by longinoa** [comment]
From a very cursory look at phonegap it doesn't seem to be obvious how the interaction with Stetho would work. Phonegap is cross platform and Stetho requires more Java and Android specific Java with the way it interops with networking and layouts
