### ISSUE TITLE
HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by JavaBoyHW** [facebook/stetho#597]
I use stetho in my App. I want to test my sqlite。I have searched Issues, but anyone can help me.
I use gradle in my app module, build.gradle:
`// Stetho core
    compile 'com.facebook.stetho:stetho:1.3.1'
    compile 'com.facebook.stetho:stetho-okhttp3:1.3.1'`
And my Application.java:
`Stetho.initializeWithDefaults(this);
        new OkHttpClient.Builder().addNetworkInterceptor(new StethoInterceptor())
                .build();`
when i install my App in my phone(huawei Android 7.0). Run my App.In my Chrome, open "chrome://inspect/#devices", click the inspect button. After a loading, I get a "HTTP/1.1 404 Not Found"：

![qq 20180515143047](https://user-images.githubusercontent.com/23182152/40040419-d15d6e9c-584c-11e8-8045-57abf9985b35.png)

**Comment by blackoutprogrammer** [comment]
Here with the same problem.
does anyone know the solution?

**Comment by shixiuwen** [comment]
Here with the same problem.
does anyone know the solution?

**Comment by blackoutprogrammer** [comment]
Hey there @JavaBoyHW 
finally i found the problem
use vpn in both mobile and your computer.
its because of google restricted this feature in your country.

**Comment by armavion** [comment]
> Hey there @JavaBoyHW
> finally i found the problem
> use vpn in both mobile and your computer.
> its because of google restricted this feature in your country.

Unfortunately that's true. I used a proxy and it's all fine.

**Comment by pallaviMN** [comment]
@armavion , can you please let me know, how did you resolve? even i am facing the same

**Comment by armavion** [comment]
@pallaviMN My IP address is from Iran, and Google doesn't really like us 😃 So basically what I did was to connect to a VPN to change my public IP. As soon as I connected to the VPN and clicked "inspect", I didn't see the 404 error anymore and it all worked.

**Comment by pallaviMN** [comment]
@armavion , actually in our office its not working but @home when i tried it works

**Comment by jasta** [comment]
Closing as this is a client connectivity issue to Google, not a Stetho issue.

**Comment by jasta** [comment]
Although note that in theory it would be possible for Stetho to ship our own copy of devtools to workaround this issue, but that is currently considered out of scope as a straight forward fix to this issue :\

**Comment by pcqpcq** [comment]
add appspot.com to proxy config works for me

**Comment by mohsen2986** [comment]
> @pallaviMN My IP address is from Iran, and Google doesn't really like us smiley So basically what I did was to connect to a VPN to change my public IP. As soon as I connected to the VPN and clicked "inspect", I didn't see the 404 error anymore and it all worked.

this is the bad part of history , im working on it about 3 h :(
