### ISSUE TITLE
HTTP/1.1 404 Not Found，and use VPN still doesn't work

### ISSUE THREAD

**Issue by liushazm** [facebook/stetho#601]
i click the inspect button, show a page only with a string "HTTP/1.1 404 Not Found"，and use VPN still doesn't work, i can open google's website, before today it works all right, anyone has the problem?

**Comment by scofieldwenwen** [comment]
use vpn in both mobile and your computer.

**Comment by wessama** [comment]
This problem isn't related to Stetho, it has to do with the Chrome version you're running on your Android device and your PC. I found the answer here: https://stackoverflow.com/questions/51519636/google-chrome-developer-tools-android-debugging-returns-http-1-1-404-not-found

Re-installing Google Chrome on my Android device does the trick for me. Though
