### ISSUE TITLE
Support for inspecting Cookies

### ISSUE THREAD

**Issue by dant3** [facebook/stetho#605]
There is a cookies inspector in chrome nearby resources like storage and database, I would love to use it to inspect our app's `CookieJar` - we use OkHttp.

**Comment by longinoa** [comment]
CookieJar in OkHttp is opaque to our layer. OkHttp adds it once you send the request to them. AFAIK there is no real way to get this out. All of the network info that we add are done as a best guess as to what the system will add. Its possible there is an interceptor for this that Im not aware of though.
