### ISSUE TITLE
No matching handler?

### ISSUE THREAD

**Issue by emitchel** [facebook/stetho#606]
I've been using Stetho for a while now on various projects, using 1.5.0

When I open up dev tools on chrome while the app is running, Logcat spews out the following message and doesn't show up as a device on //inspect
```W/stetho: I/O error: java.io.IOException: No matching handler, firstByte=71```

 2-3 times a second

Seems unique considering I haven't found any threads related to this message

**Comment by huww98** [comment]
I got the same error. After some inspection, I found this may because of the missing `.enableWebKitInspector(Stetho.defaultInspectorModulesProvider(context))` line. see https://github.com/facebook/stetho#custom-dumpapp-plugins

**Comment by emitchel** [comment]
Ugh yup, thanks @huww98
