### ISSUE TITLE
How to user Database Inspection for encrypted SQLite database

### ISSUE THREAD

**Issue by csgajcr** [facebook/stetho#610]
i'm use WCDB for my database framework.but i can't debug the database when i set database password.
i think Stetho called _DefaultDatabaseErrorHandler_ when open database failed.then my database has been delete.

**Comment by longinoa** [comment]
You will likely need to write a custom `DatabaseConnectionProvider` though I bet you would have to hardcode your password into the provider itself :(

One other thing you can try is to create a dumpapp plugin that you can keep track of state. This would allow you to send the password and then make queries.
