### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by maks** [facebook/stetho#625]
@jasta there have been a fair few commits go into master since 1.5.0 - are there any plans to do a new release?

**Comment by sudhee** [comment]
+1. Looking for a new release.

**Comment by android-notes** [comment]
+1

**Comment by alexio** [comment]
+1
@jasta  Are there any updates on a plan for a new release?

**Comment by spukki01** [comment]
+1 for a new release.

**Comment by longinoa** [comment]
@iamareebjamal - probably a good idea to open a separate issue on that. I havent explicitly done this on P yet but if there are code changes to make to support it we need to track it

**Comment by iamareebjamal** [comment]
#607 solved that as far as I know

**Comment by rachellaura-jones** [comment]
+1

**Comment by pseandersson** [comment]
+1

**Comment by brianguertin** [comment]
For anyone looking for a new build, jitpack seems to work well, so you can use any revision as a dependency by using jitpack, e.g.:
```
repositories {
    maven { url "https://jitpack.io" }
}
dependencies {
    implementation 'com.github.facebook.stetho:stetho:6d148f20b96ecb29320cced6617830eda8af0426'
}
```

**Comment by carstenhag** [comment]
@jasta @rogerhu @AlexTrotsenko Please release a new version! It's hopefully just running a script, there's no reason this is open since months now :(

**Comment by brianguertin** [comment]
Maybe first fix the JS and database consoles. Stetho is crippled in recent Chrome releases :cry:  https://github.com/facebook/stetho/issues/634

**Comment by longinoa** [comment]
@brianguertin  - I think that issue is upstream.

**Comment by jasta** [comment]
New version is incoming.  The #634 issue is indeed different though and I believe uptsream is fixing it independently.
