### ISSUE TITLE
Network inspection can't get nothing

### ISSUE THREAD

**Issue by ahaliulang** [facebook/stetho#631]
A few days ago,it worked finely.but today it suddenly can't get nothing and i don't konw why.also,I googled it but I can't get useful message.
![image](https://user-images.githubusercontent.com/18627880/49418327-93c6ed00-f7bc-11e8-82af-276dd25cc375.png)

**Comment by 0xcaff** [comment]
I am encountering the same problem too!

**Comment by 0xcaff** [comment]
My issue was that I was using `addInterceptor` instead of `addNetworkInterceptor` on the `OkHttpClientBuilder`.

**Comment by longinoa** [comment]
This is working in the sample app as of today on android 9 and chrome 72. If you are still having an issue please reopen and add more details.
