### ISSUE TITLE
App crashes android 9

### ISSUE THREAD

**Issue by kumold** [facebook/stetho#633]
When starting to inspect with chrome app crashes with error:

> Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

**Comment by k-misztal** [comment]
Same here. In my case it happens when I try to inspect layout. When the app tries to highlight the element that is being selected (hovered) in chrome console it crashes. It makes the layout inspector useless.

**Comment by giem** [comment]
I believe this is a duplicate of https://github.com/facebook/stetho/issues/607, however this still hasn't been released.

**Comment by jasta** [comment]
Release is incoming now.  1.5.1 should include the fix.
