### ISSUE TITLE
Database console not working

### ISSUE THREAD

**Issue by musooff** [facebook/stetho#635]
I am using Stetho 1.5.0
I am able to see database from resources tab of Stetho, but I am not able to query for data from database console. Say if I want to just query data
`SELECT * FROM someTable LIMIT 1; `
and hit enter, it keeps going to next line while showing indicator. No data is shown.

<img width="288" alt="screen shot 2019-02-21 at 11 38 23 am" src="https://user-images.githubusercontent.com/22423682/53139609-80623b80-35cd-11e9-901b-b733e0433eb2.png">

The same problem is happening for Stetho console. 

<img width="406" alt="screen shot 2019-02-21 at 11 39 20 am" src="https://user-images.githubusercontent.com/22423682/53139619-89eba380-35cd-11e9-95b3-e4c7cd53d776.png">

I am not sure if its a bug or any dependency I should install?

**Comment by brianguertin** [comment]
Filed specific issue for JS console: https://github.com/facebook/stetho/issues/636

I suspect something happened in Chrome land that is breaking everything. And Stetho is unmantained for ~3 years (with 10k stars!)

**Comment by longinoa** [comment]
looks to be the same as #634
