### ISSUE TITLE
Javascript Console broken in Chrome 72

### ISSUE THREAD

**Issue by brianguertin** [facebook/stetho#636]
When you press enter in the JS console, it enters a new line in Chrome and does not submit the expression to Stetho.

So, RuntimeRepl is not working at all.

Stetho: 1.5.0
Chrome: 72.x

**Comment by brianguertin** [comment]
I suspect this is a regression on Chrome's side, because:

As you type into the console, Chrome sends `Runtime.evaluate` messages to Stetho asking for "completion" of the typed content.

Since stetho does not support completion, it returns an exception.

Perhaps on seeing completion fail, Chrome no longer let's you submit?

**Comment by brianguertin** [comment]
I confirmed it works if downgrading to an older build of Chrome https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/599034/

So, I guess it's all the same issue as https://github.com/facebook/stetho/issues/634

**Comment by musooff** [comment]
Same for Mac, if I downgrade to 71.x it works. 
https://www.slimjet.com/chrome/google-chrome-old-version.php

**Comment by longinoa** [comment]
Looks like #634
