### ISSUE TITLE
how to support protobufs

### ISSUE THREAD

**Issue by Caij** [facebook/stetho#661]
not found a related document or simple

**Comment by kaushalyap** [comment]
@Caij Did you found way to debug protobuf with Stetho?

**Comment by hbmartin** [comment]
I've added protobuf support to Flipper (a Stetho replacement) in https://github.com/facebook/flipper/pull/2381
In theory the underlying library could be used for a similar implementation to support Stetho https://github.com/hbmartin/protobuf_java_to_protobufjs
