### ISSUE TITLE
Androidx

### ISSUE THREAD

**Issue by eygraber** [facebook/stetho#662]
This library is one of the few that are preventing us from turning off jetifier (which would be a big performance improvement). Are there any plans to upgrade to androidx?

**Comment by eugene-kirzhanov** [comment]
Oh, sorry. Did not notice that this has already been done, but was not released yet.

**Comment by asaudemont** [comment]
Is there a plan to migrate Stetho to AndroidX? Would love to drop Jetifier :)

**Comment by cristan** [comment]
This project is dead: Facebook works on Flipper instead (see #677). I suggest using something different (like Flipper, Chucker, the Android Studio debug tools or something else)

**Comment by mdzyuba** [comment]
The upgrade to AndroidX is done in release 1.6.0. Thanks @cristan for the pull request and contribution to the project!
