### ISSUE TITLE
dumpapp commands are failing when more than 1 device is connected

### ISSUE THREAD

**Issue by SharanuPatted** [facebook/stetho#683]
python dumpapp -p com.myapp.application
Failure to target device None: more than one device/emulator

@jasta : Do we have support of dumpapp when more than 1 device connected?

**Comment by Nilzor** [comment]
Cannot reproduce on my end. The `-p` parameter works as expected

**Comment by longinoa** [comment]
Set your environment variable 'ANDROID_SERIAL'
