### ISSUE TITLE
Windows cannot be displayed after chrome update

### ISSUE THREAD

**Issue by jiantao88** [facebook/stetho#697]
![image](https://user-images.githubusercontent.com/7411102/111265876-b5ce9b80-8664-11eb-9589-f3b0efeb43ea.png)
When I click the inspect button, the window opens to show that this is the way that network data packet capturing is not possible

There is a problem with just updating chrome. There is no problem without updating chrome
![image](https://user-images.githubusercontent.com/7411102/111266038-ef9fa200-8664-11eb-9076-a537dedc4a68.png)

**Comment by hansinator85** [comment]
Since latest Chrome update it is absolutely unusable.
Please prioritise this issue.

**Comment by jgavazzisp** [comment]
Not working for me anymore.

**Comment by kenneth-saey** [comment]
I am also having this issue, worked fine before the Chrome update, not working after the update.
In logcat I can see the following output:

```
D/ChromeDevtoolsServer: onOpen
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Page.canEmulate
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Console.setTracingBasedTimeline
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Network.setCacheDisabled
I/ResponseBodyFileManager: Cleaned up temporary network files.
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Debugger.setAsyncCallStackDepth
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Debugger.skipStackFrames
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Runtime.enable
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Worker.enable
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Timeline.enable
D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.enable
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Page.getNavigationHistory
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Worker.setAutoconnectToWorkers
D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
I/chatty: uid=10604(com.insypro.takeintakeout) StethoWorker-ma identical 3 lines
D/ChromeDevtoolsServer: Method not implemented: Not implemented: IndexedDB.requestDatabaseNames
D/ChromeDevtoolsServer: Method not implemented: Not implemented: Page.getNavigationHistory
```

When inspecting Chrome tabs by opening Chrome on my Android phone, everything shows fine, so it really looks like it's related to Stetho.

**Comment by anocean2** [comment]
I have same problem too

**Comment by kenneth-saey** [comment]
As a temporary work-around: The inspector of Microsoft Edge still works and provides exactly the same features. So it seems to be a Chrome-issue.

**Comment by haitanle** [comment]
having the same issue at the moment after Chrome self-updated 
<img width="1204" alt="Screen Shot 2021-03-17 at 11 06 26 AM" src="https://user-images.githubusercontent.com/3105371/111493664-28e31b00-8714-11eb-8f3c-55db81cd20ac.png">

**Comment by Visualrainy** [comment]
same issue, any progress on this issue??

**Comment by cemper86** [comment]
same issue

**Comment by ted-prnd** [comment]
same issue

**Comment by jiantao88** [comment]
This appears to have broken with the most recent release of Chrome and Chromium, which for me is 89.0.4389.72 on Linux x64. According to the Chrome Releases blog, that appears to be the new stable that was released two days ago.

Apparently, Google does not make older versions of Chrome available after new stable releases, but you can still get old versions of Chromium. I ultimately followed the directions of the Chromium's project Download Chromium page in the "Downloading old builds of Chrome / Chromium" section. This gave me a locally runnable version 88.0.4324.0 of Chromium in which Stetho tools do work.

Release links:

Linux x64: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/827102/
Mac OS: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/827102/
Windows: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/827102/
