### ISSUE TITLE
Chrome devTool finds my device but inspection does not show any data

### ISSUE THREAD

**Issue by TigranSarkisian** [facebook/stetho#72]
I followed steps described on https://code.facebook.com/posts/393927910787513/stetho-a-new-debugging-platform-for-android/,   Chrome devTool finds my device https://yadi.sk/i/7xcnNPdfesFqq  but inspection does not show any data https://yadi.sk/i/0Bc5pxBresFuE, https://yadi.sk/i/ifa_vnOEesFwL

**Comment by jasta** [comment]
Can you confirm that `stetho-sample` works for you?  It can be installed by checking out the source and running `gradle installDebug`, then manually starting the app on your phone.

**Comment by TigranSarkisian** [comment]
with stetho-sample inspection show correct data, the problem seems to be on my side, thank you, issue closed
