### ISSUE TITLE
When stetho support OkUrlFactory ?  ( volley+okhttp+stetho support )

### ISSUE THREAD

**Issue by vanshu** [facebook/stetho#77]
I use the volley +okhttp. Implement Android Volley with OkHttp 2.2 using OkUrlFactory . 
but from the https://github.com/square/okhttp/wiki/Interceptors  ,at last ,it'said 

<h2>Availability

OkHttp's interceptors require OkHttp 2.2 or better. Unfortunately, interceptors do not work with OkUrlFactory, or the libraries that build on it, including Retrofit ≤ 1.8 and Picasso ≤ 2.4.

```java
public class OkHttpStack extends HurlStack {
   private final OkUrlFactory okUrlFactory;
   public OkHttpStack() {
       this(new OkUrlFactory(new OkHttpClient())); 
   }
   public OkHttpStack(OkUrlFactory okUrlFactory) {
       if (okUrlFactory == null) {
           throw new NullPointerException("Client must not be null.");
       }
       this.okUrlFactory = okUrlFactory;
   }
   @Override
   protected HttpURLConnection createConnection(URL url) throws IOException {
       return okUrlFactory.open(url);
   }
}
```

**Comment by jasta** [comment]
Volley can be supported a few different ways.  There's discussion of a generic solution in #51, but the currently preferred solution for okhttp specifically is with a new `OkHttpStack` implementation: https://gist.github.com/bryanstern/4e8f1cb5a8e14c202750.

**Comment by amadib** [comment]
@jasta Considering [Apache HTTP Client Removal](http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client), how would our `HttpStack` look without having `useLibrary 'org.apache.http.legacy'`?

**Comment by lemoclone** [comment]
For stetho 1.3.1, redirect the http request by get the http request's header and body, (if just for test),here is the implementation: https://github.com/lemoclone/volley/blob/master/src/main/java/com/android/volley/toolbox/OkHttpStack.java
