### ISSUE TITLE
How can i do showing packages list on devices menu?

### ISSUE THREAD

**Issue by DongHyunKo** [facebook/stetho#78]
After including stetho, I run android app and chrome devTools.
chrome://inspect

I can see devices list like under...

Galaxy S4 - 4.3 - API 18 - 1080x1920
#192.168.56.101:5555

But I can't see package list. 

Do i need any install package in chrome?

**Comment by jasta** [comment]
It sounds like you've not invoked `Stetho.initialize`.  For comparison, you can try installing the stetho-sample and seeing if it works.  Clone from github and run `./gradlew installDebug` then tap the launcher icon.

**Comment by DongHyunKo** [comment]
Opps. I just make a mistake. 
thank for your response.
