### ISSUE TITLE
Feedback on non SELECT database queries.

### ISSUE THREAD

**Issue by Tolriq** [facebook/stetho#82]
Currently there's no feedback when doing update or delete queries.

It would be great to have some to know that it worked as even the query vanish from the interface.

Maybe use the current error system 

```
delete from albums where tt = false;
no such column: tt (code 1): , while compiling: delete from albums where tt = false;
```

With the error line containing : Success : Last id = XX or affected rows = YY

Or return a dummy cursor with only 2 columns last id , affected rows and 1 line with data.

**Comment by jasta** [comment]
I just looked into this briefly and noticed that of course you can indeed return results as if it were a SQL query.  I think that's probably the right thing to do.

Patches welcome? :)  You'd be looking at `Database` and `DatabasePeerManager`.

**Comment by Tolriq** [comment]
If no one look into that before I have time, I'll try :)

But I must admit I'm in the middle of a big rewrite and try to gain time with tools, so hard to find time soon to learn new product to contribute.

**Comment by jasta** [comment]
@Tolriq I'll see what I can do :)

**Comment by Tolriq** [comment]
No hurry the tool is already wonderful right now and make me win lot's of time for tests and debug.

So I can check that when I have time after the database / sync rewrite :)

**Comment by longinoa** [comment]
I looked into this a bit today. We are using `SqliteDatabase#rawQuery(...)` which returns a `Cursor`. As far as I can tell we cant extract the data of how many rows were modified from a `Cursor` and would need to find out if the query is `UPDATE`/`INSERT`/`DELETE`/`SELECT`/... by parsing the raw sql, and then calling structured methods on `SqlliteDatabase`. 

I know presto has parsing for sqlite but do we want to go down that path?
