### ISSUE TITLE
Database journal mode changed errors

### ISSUE THREAD

**Issue by Tolriq** [facebook/stetho#84]
When using Stetho to inspect database it seems it tries to change the journal mode of the database.

My app force writeAhead and keep a connection to the db the whole time so this generate logcat errors :

```
03-10 20:00:38.057    6477-7353/xxx E/SQLiteLog﹕ (5) statement aborts at 2: [PRAGMA journal_mode=PERSIST]
03-10 20:00:38.057    6477-7353/xxx W/SQLiteConnection﹕ Could not change the database journal mode of '/data/data/xxx/databases/xxx.db' from 'wal' to 'PERSIST' because the database is locked.  This usually means that there are other open connections to the database which prevents the database from enabling or disabling write-ahead logging mode.  Proceeding without changing the journal mode.
03-10 20:00:39.088    6477-7353/xxx E/SQLiteLog﹕ (5) statement aborts at 2: [PRAGMA journal_mode=PERSIST]
03-10 20:00:39.088    6477-7353/xxx W/SQLiteConnection﹕ Could not change the database journal mode of '/data/data/xxx/databases/xxx.db' from 'wal' to 'PERSIST' because the database is locked.  This usually means that there are other open connections to the database which prevents the database from enabling or disabling write-ahead logging mode.  Proceeding without changing the journal mode.
```

Is there a reason for that ? What are the impacts of the changes failing ?
And if you are just trying to activate writeAhead as the error suggest maybe just check before if it's not the case ?

**Comment by jasta** [comment]
The issue, I believe, is that we open the database handle ourselves rather than trying to re-use an existing connection which means that the current process may have already opened the database using different flags.  Attempting to re-open it may reconfigure details like write-ahead logging, which cannot be done while the database is locked.

For this to work, I think we'd need some way of detecting the correct configuration and applying it, but I'm not extremely familiar with this problem space and would need to investigate much deeper.  Maybe it works to just check for a `-wal` file? :)

**Comment by Tolriq** [comment]
Well this sounds more complex indeed and in the end is not error prone due to concurrency issues :(

I suppose locks would prevents database corruption and just throws errors in Stetho.

Maybe for applications that needs to keep database opens add a callback in the instance builder to ask the application for the SQLiteConnection or whatever Stetho needs on target database ?

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jasta** [comment]
Any chance we can get a PR to fix this?  I don't have time to investigate further personally and want to tidy up the issues list.

**Comment by Tolriq** [comment]
Well sorry but this is a little out of my competences to do this right :(

**Comment by jasta** [comment]
We addressed it with an extensibility layer; closing to clean up issues.
