### ISSUE TITLE
Inspect link opens up an empty window

### ISSUE THREAD

**Issue by dannysuen** [facebook/stetho#94]
I clicked the inspect link for stetho-sample on Chrome DevTools page and it opened up an empty window. How to troubleshoot this issue?

**Comment by jasta** [comment]
Are you using proguard with obfuscation on the Stetho build?  If yes, it breaks Stetho unfortunately.  Logcat confirms this by an unusual set of "Method not implemented" calls (for the common things we do implement like Network, Database, etc).

**Comment by dannysuen** [comment]
I just cloned the repo and run `./gradlew installDebug` to install the `stetho-sample` demo. Also the Logcat didn't issue "Method not implemented" warnings when the sample was run.

![Uploading 73C738B1-87DF-46EC-A785-410E0DAC9AC7.png . . .]()

**Comment by jasta** [comment]
Oh sorry, misread that this was failing for `stetho-sample` as well.  Does this machine have access to the Internet?  It does download the UI code from Google servers.

**Comment by dannysuen** [comment]
Thanks you jasta! That did resolve my issue. Google servers are blocked in China.

**Comment by codezjx** [comment]
@dannysuen Thanks!!! After I open my proxy, the window content appear. Damn GFW!!!

**Comment by androidmalin** [comment]
I meet this error,too!
