### ISSUE TITLE
Support for non-debuggable builds

### ISSUE THREAD

**Issue by hzsweers** [facebook/stetho#96]
Right now, Stetho appears to only work if the build's `debuggable` flag is enabled. I've been searching, and there doesn't seem to be any way to force enable this like you can with, say, `WebView.setWebContentsDebuggingEnabled()` (which ignores that flag).

Our use case: We serve internal betas to the rest of the company that are release builds, and distribute via private alpha channel on Google Play. Google Play doesn't allow the upload of debuggable builds, but we would like our server guys to be able to leverage Stetho for their own work without needing to build a debug build themselves.

Please let me know if I've missed anything or if this functionality is already there!

**Comment by IgorGanapolsky** [comment]
@hzsweers ~"Stetho appears to only work if the build's debuggable flag is enabled".  Not true at all.  Have you looked at stetho-sample code?  They do not have a <b>debuggable</b> flag.

**Comment by hzsweers** [comment]
The stetho sample code doesn't configure any buildTypes. This implicitly results in using the default "debug" buildType, which in turn implicitly enables the `debuggable` flag.

If you create a new buildType (say, `release`) and built that instead without setting the debug flag (or setting it to `false` to be sure), it will not work.

**Comment by jasta** [comment]
Actually it does work fine in release builds its just that proguard
obfuscation breaks our reflection based ChromeDevtoolsMethod and friends.
If you -keepnames in your proguard config for all stetho classes, it will
work.

We've been looking at fixing this (explicitly mapping methods / parameters
to strings) but it hasn't been a high priority yet.

**Comment by hzsweers** [comment]
Are you sure that's it? We have this in our proguard, and it's not enough for us:

```
-keep class com.facebook.stetho.** { *; }
```

Unless just "keep" doesn't implicitly keep names?

**Comment by jasta** [comment]
@hzsweers I debugged this issue with another user on #80 who confirmed the fix you just proposed.  I also know for sure that with obfuscation it will break.  One thing you can do just to make sure proguard is working how you expect would be to run `dexdump` as discussed in #80 to confirm that indeed the important Stetho classes (like Network, Runtime, etc) are present and their names are unobfuscated.

**Comment by hzsweers** [comment]
Huh, now that I try some more it seems to work fine. I'm wondering if maybe we still had the calls wrapped in an `if (BuildConfig.DEBUG)` call when we checked before...

Anyway, thanks for the help!
